
import java.awt.Color;
import static java.awt.Color.BLACK;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Properties;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Admin
 */
public class AdminPortal extends javax.swing.JFrame {

    private Connection con;

    /**
     * Creates new form AdminPortal
     */
    public AdminPortal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        Username = new javax.swing.JLabel();
        jTabbedPane = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        JAppointTutor = new javax.swing.JPanel();
        btnAppoint = new javax.swing.JButton();
        image = new javax.swing.JLabel();
        JManageDB = new javax.swing.JPanel();
        btnManage = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tDisplayUsers = new javax.swing.JTable();
        btnSearch1 = new javax.swing.JButton();
        btnSearch4 = new javax.swing.JButton();
        btnSearch2 = new javax.swing.JButton();
        tfStudentNo = new javax.swing.JTextField();
        JUpdate = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jProgressBar = new javax.swing.JProgressBar();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TDisplayTutorials = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(204, 153, 0));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(198, 299));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setForeground(new java.awt.Color(24, 22, 76));
        jButton5.setText("Logout");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 462, -1, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\Logo.png")); // NOI18N
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 191, -1));

        Username.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/male_user_50px.png"))); // NOI18N
        jPanel2.add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        jTabbedPane.setEnabled(false);
        jTabbedPane.setOpaque(true);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JAppointTutor.setBackground(new java.awt.Color(255, 255, 255));
        JAppointTutor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JAppointTutorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JAppointTutorMouseExited(evt);
            }
        });

        btnAppoint.setForeground(new java.awt.Color(24, 22, 76));
        btnAppoint.setText("View Tutorials");
        btnAppoint.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 153, 0), 1, true));
        btnAppoint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAppointMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAppointMouseExited(evt);
            }
        });
        btnAppoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAppointActionPerformed(evt);
            }
        });

        image.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\download (5).png")); // NOI18N

        javax.swing.GroupLayout JAppointTutorLayout = new javax.swing.GroupLayout(JAppointTutor);
        JAppointTutor.setLayout(JAppointTutorLayout);
        JAppointTutorLayout.setHorizontalGroup(
            JAppointTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JAppointTutorLayout.createSequentialGroup()
                .addGroup(JAppointTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAppoint, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JAppointTutorLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(image)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        JAppointTutorLayout.setVerticalGroup(
            JAppointTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JAppointTutorLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(image)
                .addGap(18, 18, 18)
                .addComponent(btnAppoint, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel5.add(JAppointTutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 117, -1, -1));

        JManageDB.setBackground(new java.awt.Color(255, 255, 255));
        JManageDB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JManageDBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JManageDBMouseExited(evt);
            }
        });

        btnManage.setForeground(new java.awt.Color(24, 22, 76));
        btnManage.setText("Manage Database");
        btnManage.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 153, 0), 1, true));
        btnManage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnManageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnManageMouseExited(evt);
            }
        });
        btnManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\download (6).png")); // NOI18N

        javax.swing.GroupLayout JManageDBLayout = new javax.swing.GroupLayout(JManageDB);
        JManageDB.setLayout(JManageDBLayout);
        JManageDBLayout.setHorizontalGroup(
            JManageDBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JManageDBLayout.createSequentialGroup()
                .addComponent(btnManage, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JManageDBLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(44, 44, 44))
        );
        JManageDBLayout.setVerticalGroup(
            JManageDBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JManageDBLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(btnManage, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel5.add(JManageDB, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 117, -1, -1));

        jTabbedPane.addTab("tab1", jPanel5);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        tDisplayUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Middle Name", "Last Name", "Student Number", "Role"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tDisplayUsers);

        btnSearch1.setBackground(new java.awt.Color(204, 153, 0));
        btnSearch1.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch1.setText("Search");
        btnSearch1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btnSearch1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch1ActionPerformed(evt);
            }
        });

        btnSearch4.setBackground(new java.awt.Color(204, 153, 0));
        btnSearch4.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch4.setText("Delete Record");
        btnSearch4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 153, 0), 1, true));
        btnSearch4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch4ActionPerformed(evt);
            }
        });

        btnSearch2.setBackground(new java.awt.Color(204, 153, 0));
        btnSearch2.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch2.setText("Search");
        btnSearch2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 153, 0), 1, true));
        btnSearch2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch2ActionPerformed(evt);
            }
        });

        JUpdate.setBackground(new java.awt.Color(204, 153, 0));
        JUpdate.setForeground(new java.awt.Color(255, 255, 255));
        JUpdate.setText("Change Role");
        JUpdate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 153, 0)));
        JUpdate.setEnabled(false);
        JUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JUpdateActionPerformed(evt);
            }
        });

        jLabel2.setText("Search  A Student Number To Change The Student's Role.");

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\SnBYFb99dWyo.gif")); // NOI18N
        jLabel4.setText("Back");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JUpdate)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btnSearch2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tfStudentNo, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(170, 170, 170))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(146, 146, 146))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSearch4)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 49, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(jLabel2))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(34, 34, 34)
                .addComponent(btnSearch1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearch4)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfStudentNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JUpdate)
                .addGap(18, 18, 18)
                .addComponent(jProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("tab2", jPanel4);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        TDisplayTutorials.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tutor Number", "Student Number", "Preferred Module", "Preferred Mode", "Time", "Date", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(TDisplayTutorials);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\SnBYFb99dWyo.gif")); // NOI18N
        jLabel5.setText("Back");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
        );

        jTabbedPane.addTab("tab3", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch1ActionPerformed
        // TODO add your handling code here:
        try {
            String host = "db.url";
            String uName = "db.username";
            String uPass = "db.password";
            con = DriverManager.getConnection(host, uName, uPass);

            String query = "SELECT FIRST_NAME, MIDDLE_NAME, LAST_NAME, STUDENT_NUMBER, ROLES FROM TUTORIALS";
            try (PreparedStatement pstmt = con.prepareStatement(query)) {

                try (ResultSet rs = pstmt.executeQuery()) {
                    DefaultTableModel table = (DefaultTableModel) tDisplayUsers.getModel();
                    table.setRowCount(0); // Clear existing table data

                    while (rs.next()) {
                        String firstName = rs.getString("FIRST_NAME");
                        String middleName = rs.getString("MIDDLE_NAME");
                        String lastName = rs.getString("LAST_NAME");
                        String studentNo = rs.getString("STUDENT_NUMBER");
                        boolean student = rs.getBoolean("ROLES");

                        // Add data to the table model
                        String[] rowData = {firstName, middleName, lastName, studentNo, student ? "Student" : "Tutor"};
                        table.addRow(rowData);
                    }
                }
            } catch (SQLException err) {
                JOptionPane.showMessageDialog(null, err.getMessage());
            }
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, err.getMessage());
        }
    }//GEN-LAST:event_btnSearch1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        dispose();
        studentLogin log = new studentLogin();
        log.setTitle("Login");
        log.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnSearch4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch4ActionPerformed
        // TODO add your handling code here:
        Object row = tDisplayUsers.getSelectedRow();

    }//GEN-LAST:event_btnSearch4ActionPerformed

    private void JAppointTutorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JAppointTutorMouseEntered
        // TODO add your handling code here:
        JAppointTutor.setBorder(BorderFactory.createLineBorder(BLACK, 3));
    }//GEN-LAST:event_JAppointTutorMouseEntered

    private void JManageDBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JManageDBMouseEntered
        // TODO add your handling code here:
        JManageDB.setBorder(BorderFactory.createLineBorder(BLACK, 3));
    }//GEN-LAST:event_JManageDBMouseEntered

    private void btnAppointMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAppointMouseEntered
        // TODO add your handling code here:
        btnAppoint.setBackground(new Color(204, 153, 0));
    }//GEN-LAST:event_btnAppointMouseEntered

    private void btnManageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManageMouseEntered
        // TODO add your handling code here:
        btnManage.setBackground(new Color(204, 153, 0));
    }//GEN-LAST:event_btnManageMouseEntered

    private void btnAppointMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAppointMouseExited
        // TODO add your handling code here:
        btnAppoint.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnAppointMouseExited

    private void btnManageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManageMouseExited
        // TODO add your handling code here:
        btnManage.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnManageMouseExited

    private void JAppointTutorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JAppointTutorMouseExited
        // TODO add your handling code here:
        JAppointTutor.setBorder(BorderFactory.createLineBorder(null, 0));
    }//GEN-LAST:event_JAppointTutorMouseExited

    private void JManageDBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JManageDBMouseExited
        // TODO add your handling code here:
        JManageDB.setBorder(BorderFactory.createLineBorder(null, 0));
    }//GEN-LAST:event_JManageDBMouseExited

    private void btnAppointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAppointActionPerformed
        // TODO add your handling code here:
        jTabbedPane.setSelectedIndex(2);

        try {
            String host = "db.url";
            String uName = "db.username";
            String uPass = "db.password";
            con = DriverManager.getConnection(host, uName, uPass);

            String query = "SELECT * FROM TUTORIAL_REQUESTS";
            try (PreparedStatement pstmt = con.prepareStatement(query)) {

                try (ResultSet rs = pstmt.executeQuery()) {
                    DefaultTableModel table = (DefaultTableModel) TDisplayTutorials.getModel();
                    table.setRowCount(0);

                    while (rs.next()) {
                        String tutorName = rs.getString("TUTOR_NAME");
                        String module = rs.getString("MODULE");
                        String studentNo = rs.getString("STUDENT_NO");
                        String mode = rs.getString("PREFERED_MODE");
                        String time = rs.getString("TIME");
                        String date = rs.getString("DATE");
                        String status = rs.getString("STATUS");

                        String[] data = {tutorName, studentNo, module, mode, time, date, status};
                        table.addRow(data);
                    }
                }
            }

        } catch (SQLException err) {
            JOptionPane.showMessageDialog(this, err.getMessage());
        }
    }//GEN-LAST:event_btnAppointActionPerformed

    private void btnManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageActionPerformed
        // TODO add your handling code here:
        jTabbedPane.setSelectedIndex(1);
        try {
            String host = "db.url";
            String uName = "db.username";
            String uPass = "db.password";
            con = DriverManager.getConnection(host, uName, uPass);

            String query = "SELECT FIRST_NAME, MIDDLE_NAME, LAST_NAME, STUDENT_NUMBER, ROLES FROM TUTORIALS";
            try (PreparedStatement pstmt = con.prepareStatement(query)) {

                try (ResultSet rs = pstmt.executeQuery()) {
                    DefaultTableModel table = (DefaultTableModel) tDisplayUsers.getModel();
                    table.setRowCount(0); // Clear existing table data

                    while (rs.next()) {
                        String firstName = rs.getString("FIRST_NAME");
                        String middleName = rs.getString("MIDDLE_NAME");
                        String lastName = rs.getString("LAST_NAME");
                        String studentNo = rs.getString("STUDENT_NUMBER");
                        boolean student = rs.getBoolean("ROLES");

                        // Add data to the table model
                        String[] rowData = {firstName, middleName, lastName, studentNo, student ? "Student" : "Tutor"};
                        table.addRow(rowData);
                    }
                }
            } catch (SQLException err) {
                JOptionPane.showMessageDialog(null, err.getMessage());
            }
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, err.getMessage());
        }
    }//GEN-LAST:event_btnManageActionPerformed

    private void btnSearch2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch2ActionPerformed
        // TODO add your handling code here:
        try {
            String host = "db.url";
            String uName = "db.username";
            String uPass = "db.password";
            con = DriverManager.getConnection(host, uName, uPass);

            String StudentNo = tfStudentNo.getText();

            String query = "SELECT STUDENT_NUMBER, FIRST_NAME, LAST_NAME FROM TUTORIALS WHERE STUDENT_NUMBER = ?";
            try (PreparedStatement pstmt = con.prepareStatement(query)) {
                pstmt.setString(1, StudentNo);

                try (ResultSet rs = pstmt.executeQuery()) {
                    if (rs.next()) {
                        String dbStudentNo = rs.getString("STUDENT_NUMBER");
                        String firstName = rs.getString("FIRST_NAME");
                        String lastName = rs.getString("LAST_NAME");
                        JUpdate.setEnabled(true);
                        JOptionPane.showConfirmDialog(null, "Are you sure you want " + firstName + " " + lastName + " to be  Tutor?");
                    } else {
                        JOptionPane.showMessageDialog(null, "Student number not found!!");
                    }
                }
            } catch (SQLException err) {
                JOptionPane.showMessageDialog(null, err.getMessage());
            }
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, err.getMessage());
        }
    }//GEN-LAST:event_btnSearch2ActionPerformed

    private void JUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JUpdateActionPerformed
        // TODO add your handling code here:
        try {
            String host = "db.url";
            String uName = "db.username";
            String uPass = "db.password";
            con = DriverManager.getConnection(host, uName, uPass);
            String studentNo = tfStudentNo.getText();

            // Update the role in the TUTORIALS table
            String updateQuery = "UPDATE TUTORIALS SET ROLES = false WHERE STUDENT_NUMBER = ?";
            try (PreparedStatement updateStmt = con.prepareStatement(updateQuery)) {
                updateStmt.setString(1, studentNo);

                int rowsAffected = updateStmt.executeUpdate(); // Execute the update
                if (rowsAffected > 0) {
                    JOptionPane.showMessageDialog(null, "Student role changed successfully");

                    // Retrieve email from the PROFILE table
                    String emailQuery = "SELECT EMAIL FROM PROFILE WHERE STUDENT_NO = ?";
                    try (PreparedStatement emailStmt = con.prepareStatement(emailQuery)) {
                        emailStmt.setString(1, studentNo);
                        try (ResultSet rs = emailStmt.executeQuery()) {
                            if (rs.next()) {
                                String toEmail = rs.getString("EMAIL");
                                String subject = "ITBS: Student Role Updated";
                                String body = "Your role has been updated to tutor. Login to your portal and create a tutor profile to make yourself available to students.\n";
                                body += "Thank you for using our service.";

                                // Send email
                                OTPGenerator email = new OTPGenerator();
                                email.sendEmail(toEmail, subject, body);
                            }
                        }
                    } catch (SQLException err) {
                        JOptionPane.showMessageDialog(null, "Error sending email: " + err.getMessage());
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "No student found with the provided student number");
                }
            }
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, "Database error: " + err.getMessage());
        }
    }//GEN-LAST:event_JUpdateActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        jTabbedPane.setSelectedIndex(1);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        jTabbedPane.setSelectedIndex(0);
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPortal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPortal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPortal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPortal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPortal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JAppointTutor;
    private javax.swing.JPanel JManageDB;
    private javax.swing.JButton JUpdate;
    private javax.swing.JTable TDisplayTutorials;
    private javax.swing.JLabel Username;
    private javax.swing.JButton btnAppoint;
    private javax.swing.JButton btnManage;
    private javax.swing.JButton btnSearch1;
    private javax.swing.JButton btnSearch2;
    private javax.swing.JButton btnSearch4;
    private javax.swing.JLabel image;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JProgressBar jProgressBar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tDisplayUsers;
    private javax.swing.JTextField tfStudentNo;
    // End of variables declaration//GEN-END:variables
}
