/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Admin
 */
import static java.awt.Color.blue;
import static java.awt.Color.orange;
import static java.awt.Color.red;
import java.sql.*;
import java.util.Random;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

public class ForgotPassword extends javax.swing.JFrame {

    private Connection con;

    /**
     * Creates new form ForgotPassword
     */
    public ForgotPassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        tfStudentNo = new javax.swing.JTextField();
        btnChangePass = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfPassword = new javax.swing.JPasswordField();
        tfConPassword = new javax.swing.JPasswordField();
        JOTP = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnChangePass1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblConPassword = new javax.swing.JLabel();

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\download (1).png")); // NOI18N
        jLabel12.setText("jLabel6");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel12MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel12MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(204, 153, 0));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\download.png")); // NOI18N
        jLabel6.setText("Search");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        btnChangePass.setText("Confirm");
        btnChangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePassActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Castellar", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Reset Your Password");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Enter Your Student Number Below ");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Student Number");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("New Password");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Confirm Password");

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("TO CHANGE YOUR OLD PASSWORD");

        tfPassword.setEnabled(false);
        tfPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfPasswordMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tfPasswordMouseReleased(evt);
            }
        });

        tfConPassword.setEnabled(false);
        tfConPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfConPasswordMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tfConPasswordMouseReleased(evt);
            }
        });

        JOTP.setEnabled(false);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Please Enter the OTP");

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\download (1).png")); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel2MouseReleased(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\download (1).png")); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel3MouseReleased(evt);
            }
        });

        btnChangePass1.setText("Verify");
        btnChangePass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePass1ActionPerformed(evt);
            }
        });

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Back To Login");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        lblPassword.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(204, 0, 0));
        lblPassword.setText("Weak");

        lblConPassword.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        lblConPassword.setForeground(new java.awt.Color(204, 0, 0));
        lblConPassword.setText("Passwords don't match");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel10))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel7))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(tfStudentNo, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(JOTP, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btnChangePass1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel8))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(160, 160, 160)
                                .addComponent(lblPassword)))
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(tfConPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(lblConPassword))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(btnChangePass))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel13)))
                .addGap(40, 40, 40))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfStudentNo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JOTP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(btnChangePass1)))
                .addGap(6, 6, 6)
                .addComponent(jLabel8)
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel9))
                            .addComponent(lblPassword)))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(tfConPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(lblConPassword)
                .addGap(12, 12, 12)
                .addComponent(btnChangePass)
                .addGap(10, 10, 10)
                .addComponent(jLabel13)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(189, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(174, 174, 174))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePassActionPerformed
        String password = tfPassword.getText();
        String student_no = tfStudentNo.getText();
        String conPass = tfConPassword.getText();
        studentLogin log = new studentLogin();
        String hashedPass = log.hashPassword(password);
        try {
            String host = "jdbc:derby://localhost:1527/Tutorilas";
            String uName = "user1";
            String uPass = "user1";
            con = DriverManager.getConnection(host, uName, uPass);

            String query = "UPDATE TUTORIALS SET PASSWOORD = ? WHERE STUDENT_NUMBER = ?";
            try (PreparedStatement pstmt = con.prepareStatement(query)) {
                pstmt.setString(1, hashedPass);
                pstmt.setString(2, student_no);

                int rowsAffected = pstmt.executeUpdate();
                if (rowsAffected > 0) {
                    if (password.length() < 8 || password.isEmpty()) {
                        JOptionPane.showMessageDialog(null, "Please the above errors");
                    } else if (!conPass.equals(password)) {
                        tfConPassword.setBorder(BorderFactory.createLineBorder(red));
                    } else {
                        tfConPassword.setBorder(BorderFactory.createLineBorder(blue));
                        JOptionPane.showMessageDialog(null, "Your passord has been updated successfully");
                        dispose();
                        log.setTitle("Login");
                        log.setVisible(true);
                    }
                }
            }
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, err.getMessage());
        }


    }//GEN-LAST:event_btnChangePassActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        try {
            String host = "jdbc:derby://localhost:1527/Tutorilas";
            String uName = "user1";
            String uPass = "user1";
            con = DriverManager.getConnection(host, uName, uPass);

            String StudentNo = tfStudentNo.getText();

            String query = "SELECT STUDENT_NUMBER, FIRST_NAME, LAST_NAME FROM TUTORIALS WHERE STUDENT_NUMBER = ?";
            try (PreparedStatement pstmt = con.prepareStatement(query)) {
                pstmt.setString(1, StudentNo);

                try (ResultSet rs = pstmt.executeQuery()) {
                    if (rs.next()) {
                        String firstName = rs.getString("FIRST_NAME");
                        String lastName = rs.getString("LAST_NAME");
                        String username = firstName + " " + lastName;

                        OTPGenerator email = new OTPGenerator();

                        String otp = OTPGenerator.generateOTP(4);
                        String toEmail = StudentNo + "@spu.ac.za";
                        String subject = "ITBS: OTP to change password";
                        String body = "Your OTP code is: " + otp;

                        OTPGenerator gen = new OTPGenerator();
                        gen.setOTP(otp);

                        try {
                            email.sendEmail(toEmail, subject, body);
                            JOptionPane.showConfirmDialog(null, username + ", OTP successfully sent to your Email " + toEmail);
                            JOTP.setEnabled(true);
                        } catch (Exception e) {
                            JOptionPane.showMessageDialog(null, "Failed to send email: " + e.getMessage());
                            e.printStackTrace();
                        }

                    } else {
                        JOptionPane.showMessageDialog(null, "Student Number was not found, please try again!");
                        tfPassword.setEnabled(false);
                        tfConPassword.setEnabled(false);
                    }
                }
            } catch (SQLException err) {
                JOptionPane.showMessageDialog(null, err.getMessage());
            }
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, err.getMessage());
        }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel12MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MousePressed

    private void jLabel12MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseReleased

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        // TODO add your handling code here:
        tfPassword.setEchoChar((char) 0);
    }//GEN-LAST:event_jLabel2MousePressed

    private void jLabel2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseReleased
        // TODO add your handling code here:
        tfPassword.setEchoChar((char) '*');
    }//GEN-LAST:event_jLabel2MouseReleased

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        // TODO add your handling code here:
        tfConPassword.setEchoChar((char) 0);
    }//GEN-LAST:event_jLabel3MousePressed

    private void jLabel3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseReleased
        // TODO add your handling code here:
        tfConPassword.setEchoChar((char) '*');
    }//GEN-LAST:event_jLabel3MouseReleased

    private void btnChangePass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePass1ActionPerformed
        // TODO add your handling code here:
        OTPGenerator gen = new OTPGenerator();
        String generatedOTP = gen.getOTP();

        String userOTP = JOTP.getText();
        if (userOTP.equals(generatedOTP)) {
            JOptionPane.showMessageDialog(null, "Verification Successful");
            tfPassword.setEnabled(true);
            tfConPassword.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(null, "The OTP you entered is incorrect, please try again. ");
        }
    }//GEN-LAST:event_btnChangePass1ActionPerformed

    private void tfPasswordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfPasswordMouseExited
        // TODO add your handling code here:
        String password = tfPassword.getText();
        if (password.isEmpty()) {
            tfPassword.setBorder(BorderFactory.createLineBorder(red, 1, false));
        } else {
            if (password.length() < 5) {
                lblPassword.setForeground(red);
                lblPassword.setText("Weak");
            } else if (password.length() < 8) {
                lblPassword.setForeground(orange);
                lblPassword.setText("Medium");
            } else if (password.length() >= 8) {
                lblPassword.setForeground(blue);
                lblPassword.setText("Strong");
            }
            tfPassword.setBorder(BorderFactory.createLineBorder(blue, 1, false));
        }
    }//GEN-LAST:event_tfPasswordMouseExited

    private void tfPasswordMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfPasswordMouseReleased
        // TODO add your handling code here:
        String password = tfPassword.getText();
        if (password.isEmpty()) {

            tfPassword.setBorder(BorderFactory.createLineBorder(red, 1, false));
        } else {
            if (password.length() < 5) {
                lblPassword.setForeground(red);
                lblPassword.setText("Weak");
            } else if (password.length() < 8) {
                lblPassword.setForeground(orange);
                lblPassword.setText("Medium");
            } else if (password.length() >= 8) {
                lblPassword.setForeground(blue);
                lblPassword.setText("Strong");
            }
            tfPassword.setBorder(BorderFactory.createLineBorder(blue, 1, false));
        }
    }//GEN-LAST:event_tfPasswordMouseReleased

    private void tfConPasswordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfConPasswordMouseExited
        // TODO add your handling code here:
        String Conpassword = tfConPassword.getText();
        String password = tfPassword.getText();
        if (Conpassword.isEmpty() || (!Conpassword.equals(password))) {
            lblConPassword.setVisible(true);
            tfConPassword.setBorder(BorderFactory.createLineBorder(red, 1, false));
        } else {
            lblConPassword.setVisible(false);
            tfConPassword.setBorder(BorderFactory.createLineBorder(blue, 1, false));
        }
    }//GEN-LAST:event_tfConPasswordMouseExited

    private void tfConPasswordMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfConPasswordMouseReleased
        // TODO add your handling code here:
        String Conpassword = tfConPassword.getText();
        String password = tfPassword.getText();
        if (Conpassword.isEmpty() || (!Conpassword.equals(password))) {
            lblConPassword.setVisible(true);
            tfConPassword.setBorder(BorderFactory.createLineBorder(red, 1, false));
        } else {
            lblConPassword.setVisible(false);
            tfConPassword.setBorder(BorderFactory.createLineBorder(blue, 1, false));
        }
    }//GEN-LAST:event_tfConPasswordMouseReleased

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        studentLogin log = new studentLogin();
        log.setTitle("Login");
        log.setVisible(true);
    }//GEN-LAST:event_jLabel13MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JOTP;
    private javax.swing.JButton btnChangePass;
    private javax.swing.JButton btnChangePass1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblConPassword;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JPasswordField tfConPassword;
    private javax.swing.JPasswordField tfPassword;
    private javax.swing.JTextField tfStudentNo;
    // End of variables declaration//GEN-END:variables
}
