
import java.awt.Color;
import static java.awt.Color.blue;
import static java.awt.Color.orange;
import static java.awt.Color.red;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Admin
 */
public class studentRegister extends javax.swing.JFrame {

    Connection con;
    PreparedStatement ps;
    ResultSet rs;
    Statement stmt;

    /**
     * Creates new form studentRegister
     */
    public studentRegister() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel11 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        tfFirstName = new javax.swing.JTextField();
        tfLastName = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        btnSignUp = new javax.swing.JButton();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        tfStudentNo = new javax.swing.JTextField();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        tfPassword = new javax.swing.JPasswordField();
        tfConPassword = new javax.swing.JPasswordField();
        jLabel60 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        lblStudentNo = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblConPassword = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        tfMiddleName = new javax.swing.JTextField();
        jLabel64 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel11.setBackground(new java.awt.Color(204, 153, 0));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\Abstract_Creative_Idea_Brain_Bulb_Logo-removebg-preview (002).png")); // NOI18N

        jLabel55.setBackground(new java.awt.Color(255, 255, 255));
        jLabel55.setFont(new java.awt.Font("Perpetua Titling MT", 2, 14)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(255, 255, 255));
        jLabel55.setText("sessions tailored to your academic needs.");

        jLabel65.setBackground(new java.awt.Color(255, 255, 255));
        jLabel65.setFont(new java.awt.Font("Perpetua Titling MT", 2, 14)); // NOI18N
        jLabel65.setForeground(new java.awt.Color(255, 255, 255));
        jLabel65.setText("Register now for personalized tutoring");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel65)
                    .addComponent(jLabel55))
                .addGap(30, 30, 30))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel65)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel55)
                .addGap(34, 34, 34)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPanel2AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfFirstName.setToolTipText("Student Number\n\n");
        tfFirstName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfFirstNameMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tfFirstNameMouseReleased(evt);
            }
        });
        jPanel2.add(tfFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 302, 31));

        tfLastName.setToolTipText("Password");
        tfLastName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfLastNameMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tfLastNameMouseReleased(evt);
            }
        });
        jPanel2.add(tfLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 302, 31));

        jLabel57.setForeground(new java.awt.Color(204, 153, 0));
        jLabel57.setText("Login");
        jLabel57.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel57.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel57MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel57MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel57MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel57MouseReleased(evt);
            }
        });
        jPanel2.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 500, -1, -1));

        btnSignUp.setText("Sign Up");
        btnSignUp.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 153, 0), 1, true));
        btnSignUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSignUpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSignUpMouseExited(evt);
            }
        });
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });
        jPanel2.add(btnSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, 302, 31));

        jLabel58.setBackground(new java.awt.Color(255, 255, 255));
        jLabel58.setForeground(new java.awt.Color(24, 22, 76));
        jLabel58.setText("First Name");
        jPanel2.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 70, -1));

        jLabel59.setForeground(new java.awt.Color(24, 22, 76));
        jLabel59.setText("Last Name");
        jPanel2.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        tfStudentNo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfStudentNoMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tfStudentNoMouseReleased(evt);
            }
        });
        jPanel2.add(tfStudentNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 302, 31));

        jLabel61.setForeground(new java.awt.Color(24, 22, 76));
        jLabel61.setText("Student Number");
        jPanel2.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        jLabel62.setForeground(new java.awt.Color(24, 22, 76));
        jLabel62.setText("Password");
        jPanel2.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, -1, -1));

        jLabel69.setForeground(new java.awt.Color(24, 22, 76));
        jLabel69.setText("Confirm Password");
        jPanel2.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, -1, -1));

        tfPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfPasswordMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tfPasswordMouseReleased(evt);
            }
        });
        jPanel2.add(tfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 302, 31));

        tfConPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfConPasswordMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tfConPasswordMouseReleased(evt);
            }
        });
        jPanel2.add(tfConPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 302, 31));

        jLabel60.setForeground(new java.awt.Color(204, 0, 0));
        jLabel60.setText("*");
        jPanel2.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 6, -1));

        jLabel71.setForeground(new java.awt.Color(204, 0, 0));
        jLabel71.setText("*");
        jPanel2.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 6, -1));

        jLabel72.setForeground(new java.awt.Color(204, 0, 0));
        jLabel72.setText("*");
        jPanel2.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, 6, -1));

        jLabel73.setForeground(new java.awt.Color(204, 0, 0));
        jLabel73.setText("*");
        jPanel2.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 6, -1));

        lblFirstName.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        lblFirstName.setForeground(new java.awt.Color(204, 0, 0));
        jPanel2.add(lblFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, -1, 20));

        lblLastName.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        lblLastName.setForeground(new java.awt.Color(204, 0, 0));
        jPanel2.add(lblLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 40, 20));

        lblStudentNo.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        lblStudentNo.setForeground(new java.awt.Color(204, 0, 0));
        jPanel2.add(lblStudentNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, -1, 20));

        lblPassword.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(204, 0, 0));
        jPanel2.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, -1, 20));

        lblConPassword.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        lblConPassword.setForeground(new java.awt.Color(204, 0, 0));
        jPanel2.add(lblConPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 430, 100, 20));

        jLabel2.setText("Already have an account?");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 500, -1, -1));

        jLabel63.setForeground(new java.awt.Color(204, 0, 0));
        jLabel63.setText("*");
        jPanel2.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 6, -1));

        tfMiddleName.setToolTipText("Student Number\n\n");
        tfMiddleName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfMiddleNameMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tfMiddleNameMouseReleased(evt);
            }
        });
        jPanel2.add(tfMiddleName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 302, 31));

        jLabel64.setBackground(new java.awt.Color(255, 255, 255));
        jLabel64.setForeground(new java.awt.Color(24, 22, 76));
        jLabel64.setText("Middle Name");
        jPanel2.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 80, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\download (1).png")); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel1MouseReleased(evt);
            }
        });
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\download (1).png")); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel3MouseReleased(evt);
            }
        });
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 400, -1, -1));

        jLabel5.setFont(new java.awt.Font("Castellar", 1, 24)); // NOI18N
        jLabel5.setText("REGISTRATION");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, 25));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel2AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2AncestorAdded

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        // TODO add your handling code here:
        String firstName, lastName, studentNumber, password, conPassword;

        firstName = tfFirstName.getText();
        lastName = tfLastName.getText();
        studentNumber = tfStudentNo.getText();
        password = tfPassword.getText();
        conPassword = tfConPassword.getText();

        if (firstName.isBlank()) {
            lblFirstName.setText("Required");
            tfFirstName.setBorder(BorderFactory.createLineBorder(red));
            //JOptionPane.showMessageDialog(this, "Please fill in reqired field", lastName, HEIGHT);
        } else if (lastName.isBlank()) {
            lblLastName.setText("Required");
            tfLastName.setBorder(BorderFactory.createLineBorder(red));
        } else if (studentNumber.isBlank()) {
            lblStudentNo.setText("Should be 9 Characters");
            tfStudentNo.setBorder(BorderFactory.createLineBorder(red));
        } else if (password.isBlank() || password.matches("[^a-zA-Z0-9]") || password.length() < 8) {
            tfPassword.setBorder(BorderFactory.createLineBorder(red));
        } else if (conPassword.isBlank() || (!(conPassword.equals(password)))) {
            lblConPassword.setText("Passwords don't match");
            tfConPassword.setBorder(BorderFactory.createLineBorder(red));
        } else {
            databaseConnection();
            dispose();
            studentLogin login = new studentLogin();
            login.setTitle("Login");
            login.setVisible(true);
        }
    }//GEN-LAST:event_btnSignUpActionPerformed

    private void jLabel57MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel57MouseClicked
        // TODO add your handling code here:
        dispose();
        studentLogin login = new studentLogin();
        login.setTitle("Login");
        login.setVisible(true);
    }//GEN-LAST:event_jLabel57MouseClicked

    private void jLabel57MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel57MouseEntered
        // TODO add your handling code here:
        jLabel57.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabel57MouseEntered

    private void jLabel57MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel57MouseReleased
        // TODO add your handling code here:
        jLabel57.setForeground(new Color(0, 153, 153));
    }//GEN-LAST:event_jLabel57MouseReleased

    private void jLabel57MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel57MouseExited
        // TODO add your handling code here:
        jLabel57.setForeground(new Color(0, 153, 153));
    }//GEN-LAST:event_jLabel57MouseExited

    private void tfStudentNoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfStudentNoMouseExited
        // TODO add your handling code here:
        String studentNo = tfStudentNo.getText();
        if (studentNo.length() != 9) {
            lblStudentNo.setVisible(true);
             lblStudentNo.setText("Should be 9 Characters");
            tfStudentNo.setBorder(BorderFactory.createLineBorder(red, 1, false));
        } else {
            lblStudentNo.setVisible(false);
            tfStudentNo.setBorder(BorderFactory.createLineBorder(blue, 1, false));
        }
    }//GEN-LAST:event_tfStudentNoMouseExited

    private void tfStudentNoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfStudentNoMouseReleased
        // TODO add your handling code here:
        String studentNo = tfStudentNo.getText();
        if (studentNo.length() != 9) {
            lblStudentNo.setVisible(true);
            lblStudentNo.setText("Should be 9 Characters");
            tfStudentNo.setBorder(BorderFactory.createLineBorder(red, 1, false));
        } else {
            lblStudentNo.setVisible(false);
            tfStudentNo.setBorder(BorderFactory.createLineBorder(blue, 1, false));
        }
    }//GEN-LAST:event_tfStudentNoMouseReleased

    private void tfFirstNameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfFirstNameMouseExited
        // TODO add your handling code here:
        String firstName = tfFirstName.getText();
        if (firstName.isEmpty()) {
            lblFirstName.setVisible(true);
            lblFirstName.setText("Required");
            tfFirstName.setBorder(BorderFactory.createLineBorder(red, 1, false));
        } else {
            lblFirstName.setVisible(false);
            tfFirstName.setBorder(BorderFactory.createLineBorder(blue, 1, false));
        }
    }//GEN-LAST:event_tfFirstNameMouseExited

    private void tfFirstNameMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfFirstNameMouseReleased
        // TODO add your handling code here:
        String firstName = tfFirstName.getText();
        if (firstName.isEmpty()) {
            lblFirstName.setVisible(true);
            lblFirstName.setText("Required");
            tfFirstName.setBorder(BorderFactory.createLineBorder(red, 1, false));
        } else {
            lblFirstName.setVisible(false);
            tfFirstName.setBorder(BorderFactory.createLineBorder(blue, 1, false));
        }
    }//GEN-LAST:event_tfFirstNameMouseReleased

    private void tfLastNameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfLastNameMouseExited
        // TODO add your handling code here:
        String lastName = tfLastName.getText();
        if (lastName.isEmpty()) {
            lblLastName.setVisible(true);
            lblLastName.setText("Required");
            tfLastName.setBorder(BorderFactory.createLineBorder(red, 1, false));
        } else {
            lblLastName.setVisible(false);
            tfLastName.setBorder(BorderFactory.createLineBorder(blue, 1, false));
        }
    }//GEN-LAST:event_tfLastNameMouseExited

    private void tfLastNameMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfLastNameMouseReleased
        // TODO add your handling code here:
        String lastName = tfLastName.getText();
        if (lastName.isEmpty()) {
            lblLastName.setVisible(true);
            lblLastName.setText("Required");
            tfLastName.setBorder(BorderFactory.createLineBorder(red, 1, false));
        } else {
            lblLastName.setVisible(false);
            tfLastName.setBorder(BorderFactory.createLineBorder(blue, 1, false));
        }
    }//GEN-LAST:event_tfLastNameMouseReleased

    private void tfPasswordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfPasswordMouseExited
        // TODO add your handling code here:
        String password = tfPassword.getText();
        if (password.isEmpty()) {
            tfPassword.setBorder(BorderFactory.createLineBorder(red, 1, false));
        } else {
            if (password.length() < 5) {
                lblPassword.setForeground(red);
                lblPassword.setText("Weak");
            } else if (password.length() < 8) {
                lblPassword.setForeground(orange);
                lblPassword.setText("Medium");
            } else if (password.length() >= 8) {
                lblPassword.setForeground(blue);
                lblPassword.setText("Strong");
            }
            tfPassword.setBorder(BorderFactory.createLineBorder(blue, 1, false));
        }
    }//GEN-LAST:event_tfPasswordMouseExited

    private void tfPasswordMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfPasswordMouseReleased
        // TODO add your handling code here:
        String password = tfPassword.getText();
        if (password.isEmpty()) {
            tfPassword.setBorder(BorderFactory.createLineBorder(red, 1, false));
        } else {
            if (password.length() < 5) {
                lblPassword.setForeground(red);
                lblPassword.setText("Weak");
            } else if (password.length() < 8) {
                lblPassword.setForeground(orange);
                lblPassword.setText("Medium");
            } else if (password.length() >= 8) {
                lblPassword.setForeground(blue);
                lblPassword.setText("Strong");
            }
            tfPassword.setBorder(BorderFactory.createLineBorder(blue, 1, false));
        }
    }//GEN-LAST:event_tfPasswordMouseReleased

    private void tfConPasswordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfConPasswordMouseExited
        // TODO add your handling code here:
        String Conpassword = tfConPassword.getText();
        String password = tfPassword.getText();
        if (Conpassword.isEmpty() || (!Conpassword.equals(password))) {
            lblConPassword.setVisible(true);
            lblConPassword.setText("Passwords do not match");
            tfConPassword.setBorder(BorderFactory.createLineBorder(red, 1, false));
        } else {
            lblConPassword.setVisible(false);
            tfConPassword.setBorder(BorderFactory.createLineBorder(blue, 1, false));
        }
    }//GEN-LAST:event_tfConPasswordMouseExited

    private void tfConPasswordMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfConPasswordMouseReleased
        // TODO add your handling code here:
        String Conpassword = tfConPassword.getText();
        String password = tfPassword.getText();
        if (Conpassword.isEmpty() || (!Conpassword.equals(password))) {
            lblConPassword.setVisible(true);
            lblConPassword.setText("Passwords do not match");
            tfConPassword.setBorder(BorderFactory.createLineBorder(red, 1, false));
        } else {
            lblConPassword.setVisible(false);
            tfConPassword.setBorder(BorderFactory.createLineBorder(blue, 1, false));
        }
    }//GEN-LAST:event_tfConPasswordMouseReleased

    private void tfMiddleNameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfMiddleNameMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMiddleNameMouseExited

    private void tfMiddleNameMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfMiddleNameMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMiddleNameMouseReleased

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        // TODO add your handling code here:
        tfPassword.setEchoChar((char)0);
    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseReleased
        // TODO add your handling code here:
         tfPassword.setEchoChar((char)'*');
    }//GEN-LAST:event_jLabel1MouseReleased

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        // TODO add your handling code here:
        tfConPassword.setEchoChar((char)0);
    }//GEN-LAST:event_jLabel3MousePressed

    private void jLabel3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseReleased
        // TODO add your handling code here:
        tfConPassword.setEchoChar((char)'*');
    }//GEN-LAST:event_jLabel3MouseReleased

    private void btnSignUpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignUpMouseEntered
        // TODO add your handling code here:
        btnSignUp.setBackground(new Color(204,153,0));
    }//GEN-LAST:event_btnSignUpMouseEntered

    private void btnSignUpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignUpMouseExited
        // TODO add your handling code here:
        btnSignUp.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnSignUpMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSignUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblConPassword;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblStudentNo;
    private javax.swing.JPasswordField tfConPassword;
    private javax.swing.JTextField tfFirstName;
    private javax.swing.JTextField tfLastName;
    private javax.swing.JTextField tfMiddleName;
    private javax.swing.JPasswordField tfPassword;
    private javax.swing.JTextField tfStudentNo;
    // End of variables declaration//GEN-END:variables
private void databaseConnection() {
        try {
            String host = "jdbc:derby://localhost:1527/Tutorilas";
            String uName = "user1";
            String uPass = "user1";
            con = DriverManager.getConnection(host, uName, uPass);

            String firstName = tfFirstName.getText();
            String middleName = tfMiddleName.getText();
            String lastName = tfLastName.getText();
            String studentNumber = tfStudentNo.getText();
            String password = tfPassword.getText();

            // Check if any field is empty
            if (firstName.isEmpty() || lastName.isEmpty() || studentNumber.isEmpty() || password.isEmpty()) {
                return;
            }

            // Hash the password using SHA-256
            String hashedPassword = hashPassword(password);

            
            // Prepare the SQL statement
            String query = "INSERT INTO TUTORIALS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, STUDENT_NUMBER, PASSWOORD, ROLES) VALUES (?, ?, ?, ?, ?, ?)";
            PreparedStatement ps = con.prepareStatement(query);
            ps.setString(1, firstName);
            ps.setString(2, middleName);
            ps.setString(3, lastName);
            ps.setString(4, studentNumber);
            ps.setString(5, hashedPassword); // Store hashed password
            ps.setBoolean(6, true);
            ProfileClass prof = new ProfileClass();

            // Execute the SQL statement
            int rowsAffected = ps.executeUpdate();

            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(this, "Registration successful!");
            } else {
                JOptionPane.showMessageDialog(this, "Registration failed!");
            }

            // Close resources
            ps.close();
            con.close();
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(this, err.getMessage());
        }
    }

    public String hashPassword(String password) {
        try {
            // Create MessageDigest instance for SHA-256
            MessageDigest md = MessageDigest.getInstance("SHA-256");

            // Add password bytes to digest
            md.update(password.getBytes());

            // Get the hashed bytes
            byte[] bytes = md.digest();

            // Convert bytes to hexadecimal format
            StringBuilder sb = new StringBuilder();
            for (byte b : bytes) {
                sb.append(String.format("%02x", b));
            }

            return sb.toString();
        } catch (NoSuchAlgorithmException e) {
            return null;
        }
    }
}
