/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Admin
 */
import java.awt.*;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.sql.*;
import java.sql.DriverManager;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class studentDashboard extends javax.swing.JFrame {

    private Connection con;

    /**
     * Creates new form studentDashboard
     */
    public studentDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        JRequests = new javax.swing.JButton();
        JQuiz = new javax.swing.JButton();
        JMaterial = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        JAppointments = new javax.swing.JButton();
        Username = new javax.swing.JLabel();
        JTabbedTutorials = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        JTime = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        tfModules = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jComboBox = new javax.swing.JComboBox<>();
        tfTutors = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        JAcademicLevel = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        JDateChooser = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tRequestedSession = new javax.swing.JTable();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenu3.setText("jMenu3");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        jMenuItem3.setText("jMenuItem3");

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(204, 153, 0));

        JRequests.setForeground(new java.awt.Color(24, 22, 76));
        JRequests.setText("Request Tutorial");
        JRequests.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        JRequests.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JRequestsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JRequestsMouseExited(evt);
            }
        });
        JRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRequestsActionPerformed(evt);
            }
        });

        JQuiz.setForeground(new java.awt.Color(24, 22, 76));
        JQuiz.setText("Attempt A Quiz");
        JQuiz.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        JQuiz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JQuizMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JQuizMouseExited(evt);
            }
        });
        JQuiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JQuizActionPerformed(evt);
            }
        });

        JMaterial.setForeground(new java.awt.Color(24, 22, 76));
        JMaterial.setText("Study Material");
        JMaterial.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        JMaterial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JMaterialMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JMaterialMouseExited(evt);
            }
        });
        JMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMaterialActionPerformed(evt);
            }
        });

        jButton5.setForeground(new java.awt.Color(24, 22, 76));
        jButton5.setText("Logout");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/home_24px.png"))); // NOI18N
        jLabel3.setText("Home");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel3MouseReleased(evt);
            }
        });

        JAppointments.setForeground(new java.awt.Color(24, 22, 76));
        JAppointments.setText("View Appointments");
        JAppointments.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        JAppointments.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JAppointmentsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JAppointmentsMouseExited(evt);
            }
        });
        JAppointments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JAppointmentsActionPerformed(evt);
            }
        });

        Username.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/male_user_50px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JQuiz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JMaterial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JRequests, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JAppointments, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jButton5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(Username)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(33, 33, 33)
                .addComponent(Username)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JRequests, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JAppointments, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139)
                .addComponent(jButton5)
                .addGap(28, 28, 28))
        );

        JTabbedTutorials.setEnabled(false);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Castellar", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(24, 22, 76));
        jLabel1.setText("Welcome to the Student DAHSBOARD");

        jPanel3.setBackground(new java.awt.Color(204, 153, 0));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Select Prefered Mode:");

        JTime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "08:00 AM - 10:00 AM", "10:00 AM - 12:00 PM", "12:00 PM - 14:00 PM", "14:00 PM - 16:00 PM" }));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Select Prefered Time:");

        tfModules.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        tfModules.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfModulesMouseClicked(evt);
            }
        });
        tfModules.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfModulesActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(" Module:");

        jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Contact", "Online" }));

        tfTutors.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        tfTutors.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfTutorsMouseClicked(evt);
            }
        });
        tfTutors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTutorsActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Available Tutors:");

        JAcademicLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JAcademicLevelActionPerformed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Academic Year:");

        jLabel10.setBackground(new java.awt.Color(24, 22, 76));
        jLabel10.setFont(new java.awt.Font("Castellar", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Request  A Tutor.");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Pick A date:");

        jButton6.setForeground(new java.awt.Color(24, 22, 76));
        jButton6.setText("Submit");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addGap(161, 161, 161)
                            .addComponent(jLabel10)
                            .addGap(96, 96, 96))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addGap(202, 202, 202)
                            .addComponent(JAcademicLevel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton6)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel8))
                                .addGap(56, 56, 56)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfTutors, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfModules, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(JTime, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(JDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGap(51, 51, 51))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JAcademicLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfModules, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTutors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(JTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(JDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setForeground(new java.awt.Color(24, 22, 76));
        jLabel9.setText("Please fill out the following form to request a tutor.");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(116, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(jLabel9)))))
                .addGap(95, 95, 95))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(41, 41, 41)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        JTabbedTutorials.addTab("tab1", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        tRequestedSession.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student Year", "Student Number", "Preferred Module", "Preferred Mode", "Time", "Date", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tRequestedSession);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 716, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(10, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 482, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(125, 125, 125)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(126, Short.MAX_VALUE)))
        );

        JTabbedTutorials.addTab("tab2", jPanel5);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTabbedTutorials))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(JTabbedTutorials)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRequestsActionPerformed
        // TODO add your handling code here 
        JTabbedTutorials.setSelectedIndex(0);
        try {
            String host = "jdbc:derby://localhost:1527/Tutorilas";
            String uName = "user1";
            String uPass = "user1";
            con = DriverManager.getConnection(host, uName, uPass);

            ProfileClass prof = new ProfileClass();
            String stud = prof.getStudentNo();

            String query = "SELECT COURSE, ACADEMIC_LEVEL FROM PROFILE Where STUDENT_NO = ?";
            try (PreparedStatement pstmt = con.prepareStatement(query)) {
                pstmt.setString(1, stud);
                try (ResultSet rs = pstmt.executeQuery()) {
                    if (rs.next()) {
                        String course = rs.getString("COURSE");
                        String level = rs.getString("ACADEMIC_LEVEL");

                        if (course.equals("Dip In ICT") && level.equals("1st Year")) {
                            tfModules.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Applications Development", "Web Development", "ICT Fundamentals", "Programming I", "Information Systems I", "Neworking", "SCOR", "Business Practice"}));
                        } else if (course.equals("Dip In ICT") && level.equals("2nd Year")) {
                            tfModules.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Programming II", "Software Engineering", "Informaltion Systems II", "Android Development", "TechnoPreneurShips", "Big Data", "Web Developmeng II", "Professional Communication", "Project Management"}));
                        } else if (course.equals("Dip In ICT") && level.equals("3rd Year")) {
                            tfModules.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Programming III", "Software Engineering II", "Informaltion Systems III", "Data Analysis And Visualization", "Human Computer Interaction", "Project"}));
                        } else if (course.equals("Dip In ICT") && level.equals("4th Year")) {
                            tfModules.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Advanced Data Analysis And Visualization", "Database System", "Development Software", "Project"}));
                        } else if (course.equals("Data Science") && level.equals("1st Year")) {
                            tfModules.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Introduction To Statistics", "Calculus", "Basic Organization And Architecture", "Mechanics", "Numerical Methods", "Probability Theory", "Introduction Programming In C++"}));
                        } else if (course.equals("Data Science") && level.equals("2nd Year")) {
                            tfModules.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Advance Calculus", "Distribution Theory", "Algorith Analysis And Program", "Database Systems", "Linear Algebra", "Mathematics Analysis", "Statistical Inference"}));
                        }
                    }
                }
            }
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, err.getMessage());
        }
    }//GEN-LAST:event_JRequestsActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        dispose();
        TutorDashboard dash = new TutorDashboard();
        dash.setTitle("Home Page");
        dash.displayWelcomeText();
        dash.setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        // TODO add your handling code here:
        jLabel3.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        // TODO add your handling code here:
        jLabel3.setForeground(new Color(0, 153, 153));
    }//GEN-LAST:event_jLabel3MouseExited

    private void jLabel3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseReleased
        // TODO add your handling code here:
        jLabel3.setForeground(new Color(0, 153, 153));
    }//GEN-LAST:event_jLabel3MouseReleased

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        dispose();
        studentLogin log = new studentLogin();
        log.setTitle("Login");
        log.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void tfModulesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfModulesMouseClicked
        // TODO add your handling code here:
        try {
            String host = "jdbc:derby://localhost:1527/Tutorilas";
            String uName = "user1";
            String uPass = "user1";
            con = DriverManager.getConnection(host, uName, uPass);

            ProfileClass prof = new ProfileClass();
            String stud = prof.getStudentNo();

            String query = "SELECT COURSE, ACADEMIC_LEVEL FROM PROFILE Where STUDENT_NO = ?";
            try (PreparedStatement pstmt = con.prepareStatement(query)) {
                pstmt.setString(1, stud);
                try (ResultSet rs = pstmt.executeQuery()) {
                    if (rs.next()) {
                        String course = rs.getString("COURSE");
                        String level = rs.getString("ACADEMIC_LEVEL");

                        JAcademicLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{level}));

                        if (course.equals("Dip In ICT") && level.equals("1st Year")) {
                            tfModules.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Applications Development", "Web Development", "ICT Fundamentals", "Programming I", "Information Systems I", "Neworking", "Core Curriculum I", "Core Curriculum II", "Business Practice"}));
                        } else if (course.equals("Dip In ICT") && level.equals("2nd Year")) {
                            tfModules.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Programming II", "Software Engineering", "Informaltion Systems II", "Android Development", "TechnoPreneurShips", "Big Data", "Web Developmeng II", "Professional Communication", "Project Management"}));
                        } else if (course.equals("Dip In ICT") && level.equals("3rd Year")) {
                            tfModules.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Programming III", "Software Engineering II", "Informaltion Systems III", "Data Analysis And Visualization", "Human Computer Interaction", "Project"}));
                        } else if (course.equals("Dip In ICT") && level.equals("4th Year")) {
                            tfModules.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Advanced Data Analysis And Visualization", "Database System", "Development Software", "Project", "Advanced development software", "Software Engineering", "Information Security"}));
                        } else if (course.equals("Data Science") && level.equals("1st Year")) {
                            tfModules.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Introduction To Statistics", "Calculus", "Basic Computer Organization And Architecture", "Probability Theory", "Introduction Programming In C++", "Algebra", "Core Curriculum", "Core Curriculum II", "Data Science I"}));
                        } else if (course.equals("Data Science") && level.equals("2nd Year")) {
                            tfModules.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Advance Calculus", "Distribution Theory", "Algorith Analysis And Program", "Database Systems", "Linear Algebra", "Discrete Mathematics", "Statistical Inference", "Operating Systems and Computer Networks", " "}));
                        }
                        if (course.equals("Data Science") && level.equals("3rd Year")) {
                            tfModules.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Advance Algorithm Analysis", "Data Security", "Algorith Analysis And Programming", "Database Systems", "Linea r Algebra", "Mathematics Analysis", "Statistical Inference"}));
                        }
                        if (course.equals("Computer Science") && level.equals("1st Year")) {
                            tfModules.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Calculus", "Mechanics", "Basic Computer Organization", "Core Corriculum I", "Algebra", "Numerical Methods and Mathematical Modeling", "Probability Theory", "Core Corriculum II"}));
                        }
                        if (course.equals("Computer Science") && level.equals("2nd Year")) {
                            tfModules.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Advance Calculus", "Distribution Theory", "Algorith Analysis And Program", "Database Systems", "Linear Algebra", "Discrete Mathematics", "Statistical Inference", "Operating Systems and Computer Networks"}));
                        }
                        if (course.equals("Computer Science") && level.equals("3rd Year")) {
                            tfModules.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Advance Algorithm Analysis", "Data Security", "Algorith Analysis And Programming", "Database Systems", "Linea r Algebra", "Mathematics Analysis", "Statistical Inference"}));
                        }
                    }
                }
            }
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, err.getMessage());
        }
    }//GEN-LAST:event_tfModulesMouseClicked

    private void JMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMaterialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JMaterialActionPerformed

    private void JAcademicLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JAcademicLevelActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_JAcademicLevelActionPerformed

    private void tfTutorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTutorsActionPerformed
        // TODO add your handling code here:
        try {
            String host = "jdbc:derby://localhost:1527/Tutorilas";
            String uName = "user1";
            String uPass = "user1";
            con = DriverManager.getConnection(host, uName, uPass);

            ProfileClass prof = new ProfileClass();
            String stud = prof.getStudentNo();
            Object module = tfModules.getSelectedItem();
            Object academicYear = JAcademicLevel.getSelectedItem();

            String query = "SELECT * FROM AVAILABLE_TUTORS WHERE TUTORING_MODULE = ? AND TUTORING_YEAR = ?";
            try (PreparedStatement pstmt = con.prepareStatement(query)) {
                pstmt.setObject(1, module);
                pstmt.setObject(2, academicYear);
                try (ResultSet rs = pstmt.executeQuery()) {
                    // Create a list to hold the tutors

                    ArrayList<String> tutorsList = new ArrayList();
                    while (rs.next()) {
                        String studentNo = rs.getString("STUDENT_NO");
                        String level = rs.getString("TUTORING_YEAR");
                        // Add each tutor to the list
                        tutorsList.add(studentNo + " (" + level + ")");

                    }
                    String[] tutors = tutorsList.toArray(new String[0]);
                    DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(tutors);
                    tfTutors.setModel(model);
                }
            }
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, err.getMessage());
        }
    }//GEN-LAST:event_tfTutorsActionPerformed

    private void tfModulesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfModulesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfModulesActionPerformed

    private void tfTutorsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfTutorsMouseClicked
        // TODO add your handling code here:
        try {
            String host = "jdbc:derby://localhost:1527/Tutorilas";
            String uName = "user1";
            String uPass = "user1";
            con = DriverManager.getConnection(host, uName, uPass);

            ProfileClass prof = new ProfileClass();
            String stud = prof.getStudentNo();
            Object module = tfModules.getSelectedItem();
            Object academicYear = JAcademicLevel.getSelectedItem();

            String query = "SELECT * FROM AVAILABLE_TUTORS WHERE TUTORING_MODULE = ? AND TUTORING_YEAR = ?";
            try (PreparedStatement pstmt = con.prepareStatement(query)) {
                pstmt.setObject(1, module);
                pstmt.setObject(2, academicYear);
                try (ResultSet rs = pstmt.executeQuery()) {
                    // Create a list to hold the tutors

                    ArrayList<String> tutorsList = new ArrayList();
                    while (rs.next()) {
                        String studentNo = rs.getString("STUDENT_NO");
                        String level = rs.getString("TUTORING_YEAR");
                        // Add each tutor to the list
                        tutorsList.add(studentNo);

                    }
                    if (tutorsList.isEmpty()) {
                        JOptionPane.showMessageDialog(null, "There are currently no available tutors for this module.");
                    }
                    String[] tutors = tutorsList.toArray(new String[0]);
                    DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(tutors);
                    tfTutors.setModel(model);
                }
            }
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, err.getMessage());
        }
    }//GEN-LAST:event_tfTutorsMouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        Object studentYear = JAcademicLevel.getSelectedItem();
        Object module = tfModules.getSelectedItem();
        Object tutorName = tfTutors.getSelectedItem();
        Object mode = jComboBox.getSelectedItem();
        Object time = JTime.getSelectedItem();
        Object date = JDateChooser.getDate();
        ProfileClass prof = new ProfileClass();
        String studentNo = prof.getStudentNo();
        try {
            String host = "jdbc:derby://localhost:1527/Tutorilas";
            String uName = "user1";
            String uPass = "user1";
            con = DriverManager.getConnection(host, uName, uPass);

            String query = "INSERT INTO TUTORIAL_REQUESTS (STUDENT_YEAR, MODULE, TUTOR_NAME, PREFERED_MODE, TIME, DATE, STUDENT_NO, STATUS) VALUES(?,?,?,?,?,?,?,?)";
            PreparedStatement ps = con.prepareStatement(query);
            ps.setObject(1, studentYear);
            ps.setObject(2, module);
            ps.setObject(3, tutorName);
            ps.setObject(4, mode);
            ps.setObject(5, time);
            ps.setObject(6, date);
            ps.setString(7, studentNo);
            ps.setString(8, "Pending");

            int rowsAffected = ps.executeUpdate();

            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(this, "Request successfully sent to your tutor!");
            } else {
                JOptionPane.showMessageDialog(this, "Request failed!");
            }

            // Close resources
            ps.close();
            con.close();
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, err.getMessage());
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void JQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JQuizActionPerformed
        // TODO add your handling code here:
        String course;

        try {
            String host = "jdbc:derby://localhost:1527/Tutorilas";
            String uName = "user1";
            String uPass = "user1";
            con = DriverManager.getConnection(host, uName, uPass);

            ProfileClass prof = new ProfileClass();
            String stud = prof.getStudentNo();

            String query = "SELECT COURSE, ACADEMIC_LEVEL FROM PROFILE Where STUDENT_NO = ?";
            try (PreparedStatement pstmt = con.prepareStatement(query)) {
                pstmt.setString(1, stud);
                try (ResultSet rs = pstmt.executeQuery()) {
                    if (rs.next()) {
                        course = rs.getString("COURSE");
                        if (course.equals("Dip In ICT")) {
                            try {
                                try {
                                    Desktop.getDesktop().browse(new URI("https://quizlet.com/23783090/test?funnelUUID=ef443ec0-2241-4837-a5c3-316c7f79abc3"));
                                } catch (IOException ex) {
                                    Logger.getLogger(studentDashboard.class.getName()).log(Level.SEVERE, null, ex);
                                }
                            } catch (URISyntaxException ex) {
                                Logger.getLogger(studentDashboard.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        } else if (course.equals("Data Science")) {
                            try {
                                try {
                                    Desktop.getDesktop().browse(new URI("https://quizlet.com/59076337/test?funnelUUID=8cb3d797-8f5b-483c-a06b-b98593940a66"));
                                } catch (IOException ex) {
                                    Logger.getLogger(studentDashboard.class.getName()).log(Level.SEVERE, null, ex);
                                }
                            } catch (URISyntaxException ex) {
                                Logger.getLogger(studentDashboard.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        } else if (course.equals("Computer Science")) {
                            try {
                                try {
                                    Desktop.getDesktop().browse(new URI("https://quizlet.com/22026755/test?funnelUUID=5cc86a1c-9299-4fc5-9550-3dda441ca491"));
                                } catch (URISyntaxException ex) {
                                    Logger.getLogger(studentDashboard.class.getName()).log(Level.SEVERE, null, ex);
                                }
                            } catch (IOException ex) {
                                Logger.getLogger(studentDashboard.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        }
                    }
                }
            }
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, err.getMessage());
        }
    }//GEN-LAST:event_JQuizActionPerformed

    private void JAppointmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JAppointmentsActionPerformed
        // TODO add your handling code here:
        JTabbedTutorials.setSelectedIndex(1);
        String status = "Approved";
        ProfileClass prof = new ProfileClass();
        String StudentNo = prof.getStudentNo();

        try {
            String host = "jdbc:derby://localhost:1527/Tutorilas";
            String uName = "user1";
            String uPass = "user1";
            con = DriverManager.getConnection(host, uName, uPass);

            String query = "SELECT STUDENT_YEAR, MODULE, TUTOR_NAME, PREFERED_MODE, TIME, DATE, STUDENT_NO, STATUS FROM TUTORIAL_REQUESTS WHERE STATUS = ? AND STUDENT_NO = ?";
// Specify ResultSet.TYPE_SCROLL_INSENSITIVE and ResultSet.CONCUR_READ_ONLY for a scrollable ResultSet
            try (PreparedStatement pstmt = con.prepareStatement(query, ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY)) {
                pstmt.setString(1, status);
                pstmt.setString(2, StudentNo);

                try (ResultSet rs = pstmt.executeQuery()) {
                    DefaultTableModel table = (DefaultTableModel) tRequestedSession.getModel();
                    table.setRowCount(0);
                    if (!rs.isBeforeFirst()) {
                        JOptionPane.showMessageDialog(null, "Your Tutor has not responded to your request.");
                    } else {
                        while (rs.next()) {
                            String name = rs.getString("TUTOR_NAME");
                            String studentNo = rs.getString("STUDENT_NO");
                            String module = rs.getString("MODULE");
                            String mode = rs.getString("PREFERED_MODE");
                            String time = rs.getString("TIME");
                            String date = rs.getString("DATE");
                            String dbStatus = rs.getString("STATUS");

                            String[] rowData = {name, studentNo, module, mode, time, date, dbStatus};
                            table.addRow(rowData);

                        }
                    }
                }
            } catch (SQLException err) {
                JOptionPane.showMessageDialog(null, err.getMessage());
            }
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, err.getMessage());
        }
    }//GEN-LAST:event_JAppointmentsActionPerformed

    private void JRequestsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JRequestsMouseEntered
        // TODO add your handling code here:
        JRequests.setBackground(new Color(204,153,0));
    }//GEN-LAST:event_JRequestsMouseEntered

    private void JRequestsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JRequestsMouseExited
        // TODO add your handling code here:
        JRequests.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_JRequestsMouseExited

    private void JAppointmentsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JAppointmentsMouseEntered
        // TODO add your handling code here:
        JAppointments.setBackground(new Color(204,153,0));
    }//GEN-LAST:event_JAppointmentsMouseEntered

    private void JAppointmentsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JAppointmentsMouseExited
        // TODO add your handling code here:
         JAppointments.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_JAppointmentsMouseExited

    private void JQuizMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JQuizMouseEntered
        // TODO add your handling code here:
        JQuiz.setBackground(new Color(204,153,0));
    }//GEN-LAST:event_JQuizMouseEntered

    private void JQuizMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JQuizMouseExited
        // TODO add your handling code here:
        JQuiz.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_JQuizMouseExited

    private void JMaterialMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JMaterialMouseEntered
        // TODO add your handling code here:
        JMaterial.setBackground(new Color(204,153,0));
    }//GEN-LAST:event_JMaterialMouseEntered

    private void JMaterialMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JMaterialMouseExited
        // TODO add your handling code here:
        JMaterial.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_JMaterialMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentDashboard.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentDashboard.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentDashboard.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentDashboard.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JAcademicLevel;
    private javax.swing.JButton JAppointments;
    private com.toedter.calendar.JDateChooser JDateChooser;
    private javax.swing.JButton JMaterial;
    private javax.swing.JButton JQuiz;
    private javax.swing.JButton JRequests;
    public javax.swing.JTabbedPane JTabbedTutorials;
    private javax.swing.JComboBox<String> JTime;
    private javax.swing.JLabel Username;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable tRequestedSession;
    private javax.swing.JComboBox<String> tfModules;
    private javax.swing.JComboBox<String> tfTutors;
    // End of variables declaration//GEN-END:variables

    private void setModel(DefaultComboBoxModel<String> defaultComboBoxModel) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
