
import java.awt.Color;
import static java.awt.Color.BLACK;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.BorderFactory;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Admin
 */
public class TutorDashboard extends javax.swing.JFrame {

    private Connection con;
    private PreparedStatement pstmt;
    private ResultSet rs;

    /**
     * Creates new form tutorDashboard
     */
    public TutorDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        txtUsername = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Username = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        JNames = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        WelcomeText = new javax.swing.JLabel();
        jGrades = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnTutorials = new javax.swing.JButton();
        Profile = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnProfile = new javax.swing.JButton();
        JCalender = new javax.swing.JPanel();
        btnCalender = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        JProfile = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnDashboard = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel11.setBackground(new java.awt.Color(204, 153, 0));
        jPanel11.setDoubleBuffered(false);

        jButton1.setForeground(new java.awt.Color(24, 22, 76));
        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtUsername.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(204, 153, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Username.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/male_user_50px.png"))); // NOI18N
        jPanel1.add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        lblName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 100, -1));

        JNames.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JNames.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(JNames, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 100, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\Logo.png")); // NOI18N

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(txtUsername))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(39, 39, 39))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPanel2AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        WelcomeText.setBackground(new java.awt.Color(255, 255, 255));
        WelcomeText.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        WelcomeText.setForeground(new java.awt.Color(0, 153, 153));

        jGrades.setBackground(new java.awt.Color(255, 255, 255));
        jGrades.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jGrades.setPreferredSize(new java.awt.Dimension(165, 359));
        jGrades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jGradesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jGradesMouseExited(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\images (1).jpeg")); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));

        btnTutorials.setText("My Study Plan");
        btnTutorials.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 153, 0), 1, true));
        btnTutorials.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTutorialsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTutorialsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnTutorialsMousePressed(evt);
            }
        });
        btnTutorials.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTutorialsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jGradesLayout = new javax.swing.GroupLayout(jGrades);
        jGrades.setLayout(jGradesLayout);
        jGradesLayout.setHorizontalGroup(
            jGradesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jGradesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jGradesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jGradesLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jGradesLayout.createSequentialGroup()
                        .addComponent(btnTutorials, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jGradesLayout.setVerticalGroup(
            jGradesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jGradesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnTutorials, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Profile.setBackground(new java.awt.Color(255, 255, 255));
        Profile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ProfileMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ProfileMouseExited(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\download (2).png")); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));

        btnProfile.setText("Student Profile");
        btnProfile.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 153, 0), 1, true));
        btnProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProfileMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProfileMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnProfileMousePressed(evt);
            }
        });
        btnProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ProfileLayout = new javax.swing.GroupLayout(Profile);
        Profile.setLayout(ProfileLayout);
        ProfileLayout.setHorizontalGroup(
            ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfileLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(ProfileLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        ProfileLayout.setVerticalGroup(
            ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfileLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(btnProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        JCalender.setBackground(new java.awt.Color(255, 255, 255));
        JCalender.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JCalender.setPreferredSize(new java.awt.Dimension(165, 0));
        JCalender.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JCalenderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JCalenderMouseExited(evt);
            }
        });

        btnCalender.setText("Calender");
        btnCalender.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 153, 0), 1, true));
        btnCalender.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCalenderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCalenderMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCalenderMousePressed(evt);
            }
        });
        btnCalender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalenderActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\Appointments.png")); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));

        javax.swing.GroupLayout JCalenderLayout = new javax.swing.GroupLayout(JCalender);
        JCalender.setLayout(JCalenderLayout);
        JCalenderLayout.setHorizontalGroup(
            JCalenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCalender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(JCalenderLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );
        JCalenderLayout.setVerticalGroup(
            JCalenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JCalenderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(btnCalender, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        JProfile.setBackground(new java.awt.Color(255, 255, 255));
        JProfile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JProfile.setPreferredSize(new java.awt.Dimension(165, 91));
        JProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JProfileMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JProfileMouseExited(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\download (3).png")); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));

        btnDashboard.setText("Dashboard");
        btnDashboard.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 153, 0), 1, true));
        btnDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDashboardMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnDashboardMousePressed(evt);
            }
        });
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JProfileLayout = new javax.swing.GroupLayout(JProfile);
        JProfile.setLayout(JProfileLayout);
        JProfileLayout.setHorizontalGroup(
            JProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JProfileLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(btnDashboard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JProfileLayout.setVerticalGroup(
            JProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JProfileLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(43, 43, 43)
                .addComponent(btnDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Profile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jGrades, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JProfile, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                            .addComponent(JCalender, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(33, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(WelcomeText)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(WelcomeText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Profile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JProfile, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jGrades, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                    .addComponent(JCalender, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel2AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2AncestorAdded

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
        studentLogin login = new studentLogin();
        login.setTitle("Login");
        login.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jGradesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jGradesMouseEntered
        // TODO add your handling code here:
        jGrades.setBorder(BorderFactory.createLineBorder( BLACK, 3));
    }//GEN-LAST:event_jGradesMouseEntered

    private void jGradesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jGradesMouseExited
        // TODO add your handling code here:
        jGrades.setBorder(BorderFactory.createLineBorder(null, 0));
    }//GEN-LAST:event_jGradesMouseExited

    private void JProfileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JProfileMouseEntered
        // TODO add your handling code here:
        JProfile.setBorder(BorderFactory.createLineBorder( BLACK, 3));
    }//GEN-LAST:event_JProfileMouseEntered

    private void JProfileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JProfileMouseExited
        // TODO add your handling code here:
        JProfile.setBorder(BorderFactory.createLineBorder(null, 0));
    }//GEN-LAST:event_JProfileMouseExited

    private void btnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileActionPerformed
        // TODO add your handling code here:
        /* int newWidth = 350;
        int newHeight = 361;

        // Calculate the new X position to keep the left edge fixed
        int newX = JProfile.getX() + JProfile.getWidth() - newWidth;

        // Set the new bounds for the panel
        JProfile.setBounds(newX, JProfile.getY(), newWidth, newHeight);*/
        dispose();
        Profile profile = new Profile();
        profile.setTitle("Profile");
        ProfileClass prof = new ProfileClass();
        profile.JEmail.setText(prof.getStudentNo() + "@spu.ac.za");
        profile.setVisible(true);


    }//GEN-LAST:event_btnProfileActionPerformed

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        // TODO add your handling code here:
        try {
            String host = "jdbc:derby://localhost:1527/Tutorilas";
            String uName = "user1";
            String uPass = "user1";
            Connection con = DriverManager.getConnection(host, uName, uPass);

            String query = "SELECT ROLES FROM TUTORIALS WHERE STUDENT_NUMBER = ?";

            ProfileClass prof = new ProfileClass();
            String studentNumber = prof.getStudentNo();

            try (PreparedStatement pstmt = con.prepareStatement(query)) {
                pstmt.setString(1, studentNumber);

                try (ResultSet rs = pstmt.executeQuery()) {
                    if (rs.next()) {
                        boolean isStudent = rs.getBoolean("ROLES");

                        dispose();
                        if (isStudent) {
                            studentDashboard dash = new studentDashboard();
                            dash.setTitle("Student Dashboard");
                            dash.setVisible(true);
                        } else {
                            tutorDash dash = new tutorDash();
                            dash.setTitle("Tutor Dashboard");
                            dash.setVisible(true);
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "User not found", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
            } catch (SQLException err) {
                JOptionPane.showMessageDialog(null, err.getMessage());
            }
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, err.getMessage());
        }
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void ProfileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfileMouseExited
        // TODO add your handling code here:
        Profile.setBorder(BorderFactory.createLineBorder(null, 0));
    }//GEN-LAST:event_ProfileMouseExited

    private void ProfileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfileMouseEntered
        // TODO add your handling code here:
        Profile.setBorder(BorderFactory.createLineBorder( BLACK, 3));
    }//GEN-LAST:event_ProfileMouseEntered

    private void JCalenderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JCalenderMouseExited
        // TODO add your handling code here:
        JCalender.setBorder(BorderFactory.createLineBorder(null, 0));
    }//GEN-LAST:event_JCalenderMouseExited

    private void JCalenderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JCalenderMouseEntered
        // TODO add your handling code here:
        JCalender.setBorder(BorderFactory.createLineBorder(BLACK, 3));
    }//GEN-LAST:event_JCalenderMouseEntered

    private void btnProfileMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProfileMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProfileMousePressed

    private void btnDashboardMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashboardMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnDashboardMousePressed

    private void btnTutorialsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTutorialsMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnTutorialsMousePressed

    private void btnProfileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProfileMouseEntered
        // TODO add your handling code here:
         btnProfile.setBackground(new Color(204,153,0));
    }//GEN-LAST:event_btnProfileMouseEntered

    private void btnDashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashboardMouseEntered
        // TODO add your handling code here:
        btnDashboard.setBackground(new Color(204,153,0));
    }//GEN-LAST:event_btnDashboardMouseEntered

    private void btnTutorialsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTutorialsMouseEntered
        // TODO add your handling code here:.
        btnTutorials.setBackground(new Color(204,153,0));
    }//GEN-LAST:event_btnTutorialsMouseEntered

    private void btnProfileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProfileMouseExited
        // TODO add your handling code here:
        btnProfile.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnProfileMouseExited

    private void btnDashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashboardMouseExited
        // TODO add your handling code here:
        btnDashboard.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnDashboardMouseExited

    private void btnTutorialsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTutorialsMouseExited
        // TODO add your handling code here:
        btnTutorials.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnTutorialsMouseExited

    private void btnTutorialsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutorialsActionPerformed
                              
}
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTutorialsActionPerformed

    private void btnCalenderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCalenderMouseEntered
        // TODO add your handling code here:
         btnCalender.setBackground(new Color(204,153,0));
    }//GEN-LAST:event_btnCalenderMouseEntered

    private void btnCalenderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCalenderMouseExited
        // TODO add your handling code here:
         btnCalender.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnCalenderMouseExited

    private void btnCalenderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCalenderMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalenderMousePressed

    private void btnCalenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalenderActionPerformed
        // TODO add your handling code here:
        Calendar call = new Calendar();
        call.setTitle("Calendar");
        call.setVisible(true);
    }//GEN-LAST:event_btnCalenderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TutorDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JCalender;
    private javax.swing.JLabel JNames;
    private javax.swing.JPanel JProfile;
    private javax.swing.JPanel Profile;
    private javax.swing.JLabel Username;
    public javax.swing.JLabel WelcomeText;
    private javax.swing.JButton btnCalender;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnProfile;
    private javax.swing.JButton btnTutorials;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jGrades;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public static javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private transient javax.swing.JLabel lblName;
    public javax.swing.JLabel txtUsername;
    // End of variables declaration//GEN-END:variables

    public void displayWelcomeText() {
        ProfileClass prof = new ProfileClass();
        String studenNumer = prof.getStudentNo();

        try {
            String host = "jdbc:derby://localhost:1527/Tutorilas";
            String uName = "user1";
            String uPass = "user1";
            con = DriverManager.getConnection(host, uName, uPass);

            String query = "SELECT PASSWOORD, FIRST_NAME, LAST_NAME FROM TUTORIALS WHERE STUDENT_NUMBER = ?";
            try (PreparedStatement pstmt = con.prepareStatement(query)) {
                pstmt.setString(1, studenNumer);
                try (ResultSet rs = pstmt.executeQuery()) {
                    if (rs.next()) {
                        String firstName = rs.getString("FIRST_NAME");
                        prof.setFirstName(firstName);
                        String lastName = rs.getString("LAST_NAME");
                        String Welcome = "WELCOME TO OUR TUTOR BOOKING SYSTEM "+ firstName+ "!";
                        //btnProfile.setBorder(BorderFactory.createLineBorder(new Color(204,153,0), 1, true));
                        //btnDashboard.setBorder(BorderFactory.createLineBorder(new Color(204,153,0), 1, true));
                        //btnTutorials.setBorder(BorderFactory.createLineBorder(new Color(204,153,0), 1, true));
                        WelcomeText.setForeground(BLACK);
                        WelcomeText.setFont(new Font("Montserrat", Font.PLAIN, 24));
                        WelcomeText.setText(Welcome);
                        
                        JNames.setText(firstName + " " + lastName);
                    }
                }
            }
        } catch (SQLException err) {

        }

    }
}
