/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Admin
 */
import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class tutorDash extends javax.swing.JFrame {

    private Connection con;

    /**
     * Creates new form tutorDash
     */
    public tutorDash() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        JProfile = new javax.swing.JButton();
        JRequests = new javax.swing.JButton();
        JAppointments = new javax.swing.JButton();
        JClaims = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        JTabbedPane = new javax.swing.JTabbedPane();
        JTabbedRequests = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        JAvailableSlot = new javax.swing.JComboBox<>();
        JAcademicLevel = new javax.swing.JComboBox<>();
        tfModules = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JCourse = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        JPreferredMode = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TDisplayStudents = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        JReason = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TApprovedStudents = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        tfTutorName = new javax.swing.JTextField();
        tfStudentName = new javax.swing.JTextField();
        tfDuration = new javax.swing.JTextField();
        tfModule = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnSubmit = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(204, 153, 0));

        JProfile.setText("Tutor Profile");
        JProfile.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        JProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JProfileMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JProfileMouseExited(evt);
            }
        });
        JProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JProfileActionPerformed(evt);
            }
        });

        JRequests.setText("View Requests");
        JRequests.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        JRequests.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JRequestsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JRequestsMouseExited(evt);
            }
        });
        JRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRequestsActionPerformed(evt);
            }
        });

        JAppointments.setText("View Appointments");
        JAppointments.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        JAppointments.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JAppointmentsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JAppointmentsMouseExited(evt);
            }
        });
        JAppointments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JAppointmentsActionPerformed(evt);
            }
        });

        JClaims.setText("Claim Forms");
        JClaims.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        JClaims.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JClaimsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JClaimsMouseExited(evt);
            }
        });
        JClaims.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JClaimsActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home_24px.png"))); // NOI18N
        jLabel3.setText("Home");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel3MouseReleased(evt);
            }
        });

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\download (8).png")); // NOI18N
        jLabel13.setText("Switch User");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel13MouseEntered(evt);
            }
        });

        jLabel22.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\Logo.png")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(JProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JRequests, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JAppointments, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JClaims, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JRequests, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JAppointments, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JClaims, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121))
        );

        JTabbedRequests.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(204, 153, 0));
        jPanel3.setForeground(new java.awt.Color(0, 153, 153));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Preferred Year of Study:");

        jLabel5.setBackground(new java.awt.Color(0, 153, 153));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Available Time Slot:");

        JAvailableSlot.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "08:00AM - 16:00PM ", "08:00AM - 14:00PM", "08:00AM - 12:00PM", "08:00AM - 10:00PM", " " }));
        JAvailableSlot.setToolTipText("Select the time slot you are available.");
        JAvailableSlot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JAvailableSlotActionPerformed(evt);
            }
        });

        JAcademicLevel.setToolTipText("Select the preferred year of study for your tutoring.");
        JAcademicLevel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JAcademicLevelMouseClicked(evt);
            }
        });

        tfModules.setToolTipText("Select the module you are comfortable tutoring");
        tfModules.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfModulesMouseClicked(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Preferred Course:");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Preferred Module:");

        JCourse.setToolTipText("Select the course you prefer to tutor.");
        JCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JCourseMouseClicked(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Prefered Mode:");

        jButton5.setText("Submit");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        JPreferredMode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Contact", "Online", "Hybrid" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JAcademicLevel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfModules, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JAvailableSlot, 0, 252, Short.MAX_VALUE)
                            .addComponent(JCourse, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JPreferredMode, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(48, 48, 48))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JAcademicLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfModules, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JAvailableSlot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(JPreferredMode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Castellar", 0, 18)); // NOI18N
        jLabel8.setText("Welcome to the tutor DAHSBOARD");

        jLabel9.setText("Please fill out the following form to specify your preferences.");

        jLabel10.setText("This will help us match you with the appropriate students.");

        javax.swing.GroupLayout JTabbedRequestsLayout = new javax.swing.GroupLayout(JTabbedRequests);
        JTabbedRequests.setLayout(JTabbedRequestsLayout);
        JTabbedRequestsLayout.setHorizontalGroup(
            JTabbedRequestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JTabbedRequestsLayout.createSequentialGroup()
                .addGroup(JTabbedRequestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JTabbedRequestsLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addGroup(JTabbedRequestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(JTabbedRequestsLayout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(JTabbedRequestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addGroup(JTabbedRequestsLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel10))))))
                    .addGroup(JTabbedRequestsLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        JTabbedRequestsLayout.setVerticalGroup(
            JTabbedRequestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JTabbedRequestsLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(30, 30, 30)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        JTabbedPane.addTab("tab1", JTabbedRequests);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        TDisplayStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "My Student Number", "Student Number", "Preferred Module", "Preferred Mode", "Time", "Date", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TDisplayStudents);

        jLabel7.setFont(new java.awt.Font("Castellar", 0, 14)); // NOI18N
        jLabel7.setText("if any Student requested a tutorial.");

        jButton6.setBackground(new java.awt.Color(204, 153, 0));
        jButton6.setText("Reject Request");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(204, 153, 0));
        jButton8.setText("Accept Request");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Castellar", 0, 14)); // NOI18N
        jLabel12.setText("Search The Table below to check ");

        jLabel23.setText("Reason for rejection:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jLabel7))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(jLabel12)))
                .addGap(0, 192, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jButton8)
                        .addGap(123, 123, 123)
                        .addComponent(jButton6)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JReason, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(74, 74, 74)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JReason, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        JTabbedPane.addTab("tab2", jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        TApprovedStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student Year", "Student Number", "Preferred Module", "Preferred Mode", "Time", "Date", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TApprovedStudents);

        jLabel15.setFont(new java.awt.Font("Castellar", 0, 14)); // NOI18N
        jLabel15.setText("All The STudents You HAVE AN APPOINTMENT WITH.");

        jLabel16.setFont(new java.awt.Font("Castellar", 0, 14)); // NOI18N
        jLabel16.setText("Search The Table below to VIEW ");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(jLabel16))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jLabel15)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );

        JTabbedPane.addTab("tab3", jPanel6);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(204, 153, 0));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Tutor Name:");

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Student Name:");

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Session Duration:");

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Module:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("The session is R50.00 per hour.");

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Tutor's Reflection:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSubmit)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel11)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel21))
                        .addGap(69, 69, 69)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(tfTutorName)
                            .addComponent(tfStudentName, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                            .addComponent(tfDuration, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                            .addComponent(tfModule, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE))))
                .addGap(48, 48, 48))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(jLabel19)
                .addContainerGap(178, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel19)
                .addGap(27, 27, 27)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTutorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfModule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(26, 26, 26)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(28, 28, 28)
                .addComponent(btnSubmit)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel20.setText("Claim form information.");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(124, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(268, 268, 268))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        JTabbedPane.addTab("tab4", jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(JTabbedPane))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JTabbedPane)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        dispose();
        TutorDashboard dash = new TutorDashboard();
        dash.setTitle("Home Page");
        dash.displayWelcomeText();
        dash.setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        // TODO add your handling code here:
        jLabel3.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        // TODO add your handling code here:
        jLabel3.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel3MouseExited

    private void jLabel3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseReleased
        // TODO add your handling code here:
        jLabel3.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel3MouseReleased

    private void JCourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JCourseMouseClicked
        // TODO add your handling code here:
        try {
            String host = "jdbc:derby://localhost:1527/Tutorilas";
            String uName = "user1";
            String uPass = "user1";
            con = DriverManager.getConnection(host, uName, uPass);

            String query = "SELECT COURSE, ACADEMIC_LEVEL FROM PROFILE WHERE STUDENT_NO = ?";
            ProfileClass prof = new ProfileClass();
            String studentNumber = prof.getStudentNo();

            try (PreparedStatement pstmt = con.prepareStatement(query)) {
                pstmt.setString(1, studentNumber);

                try (ResultSet rs = pstmt.executeQuery()) {
                    if (rs.next()) {
                        String course = rs.getString("COURSE");
                        String year = rs.getString("ACADEMIC_LEVEL");
                        JCourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{course}));
                        JCourse.setEditable(false);

                        switch (year) {
                            case "2nd Year" ->
                                JAcademicLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"1st Year"}));
                            case "3rd Year" ->
                                JAcademicLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"1st Year", "2nd Year"}));
                            case "4th Year" ->
                                JAcademicLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"1st Year", "2nd Year", "3rd Year"}));
                            default -> {
                            }
                        }

                    }
                }
            }
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, err.getMessage());
        }
    }//GEN-LAST:event_JCourseMouseClicked

    private void tfModulesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfModulesMouseClicked
        // TODO add your handling code here:
        Object preferedYear = JAcademicLevel.getSelectedItem();
        Object course = JCourse.getSelectedItem();

        if (course.equals("Dip In ICT") && preferedYear.equals("1st Year")) {
            tfModules.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Applications Development", "Web Development", "ICT Fundamentals", "Programming I", "Information Systems I", "Neworking", "SCOR", "Business Practice"}));
        } else if (course.equals("Dip In ICT") && preferedYear.equals("2nd Year")) {
            tfModules.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Programming II", "Software Engineering", "Informaltion Systems II", "Android Development", "TechnoPreneurShips", "Big Data", "Web Developmeng II", "Professional Communication", "Project Management"}));
        } else if (course.equals("Dip In ICT") && preferedYear.equals("3rd Year")) {
            tfModules.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Programming III", "Software Engineering II", "Informaltion Systems III", "Data Analysis And Visualization", "Human Computer Interaction", "Project"}));
        }
    }//GEN-LAST:event_tfModulesMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Object tutorCourse = JCourse.getSelectedItem();
        Object tutoringYear = JAcademicLevel.getSelectedItem();
        Object tutoringModule = tfModules.getSelectedItem();
        Object availableSlot = JAvailableSlot.getSelectedItem();
        Object availablity = JAvailableSlot.getSelectedItem();

        ProfileClass prof = new ProfileClass();
        String studentNo = prof.getStudentNo();
        try {
            String host = "jdbc:derby://localhost:1527/Tutorilas";
            String uName = "user1";
            String uPass = "user1";
            con = DriverManager.getConnection(host, uName, uPass);

            String query = "INSERT INTO AVAILABLE_TUTORS (TUTOR_COURSE, TUTORING_YEAR, TUTORING_MODULE, AVAILABLE_SLOT, PREFERED_MODE, STUDENT_NO) VALUES(?,?,?,?,?,?)";
            PreparedStatement ps = con.prepareStatement(query);

            ps.setObject(1, tutorCourse);
            ps.setObject(2, tutoringYear);
            ps.setObject(3, tutoringModule);
            ps.setObject(4, availableSlot);
            ps.setObject(5, availablity);
            ps.setObject(6, studentNo);

            int rowsAffected = ps.executeUpdate();

            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(this, "Submitted successful!");
            } else {
                JOptionPane.showMessageDialog(this, "Submission Failed failed!");
            }

            // Close resources
            ps.close();
            con.close();
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(this, err.getMessage());
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void JAvailableSlotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JAvailableSlotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JAvailableSlotActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
          // TODO add your handling code here:
        String status = "Rejected"; // 
        ProfileClass prof = new ProfileClass();
        String tutorName = prof.getStudentNo();

// Assuming your JTable instance is named "TDisplayStudents"
        String reason = JReason.getText();
        if (reason.isBlank()) {
            JOptionPane.showMessageDialog(null, "Please enter a reason for rejection");
        } else {

            int selectedRow = TDisplayStudents.getSelectedRow();
            if (selectedRow != -1) {
                try {
                    DefaultTableModel model = (DefaultTableModel) TDisplayStudents.getModel();
                    String userStudentNo = (String) model.getValueAt(selectedRow, 1);
                    String tutorResponse = status;

                    String host = "jdbc:derby://localhost:1527/Tutorilas";
                    String uName = "user1";
                    String uPass = "user1";
                    con = DriverManager.getConnection(host, uName, uPass);

                    // Update the status in the database
                    String updateQuery = "UPDATE TUTORIAL_REQUESTS SET STATUS = ? WHERE STUDENT_NO = ? AND TUTOR_NAME = ?";
                    try (PreparedStatement updateStmt = con.prepareStatement(updateQuery)) {
                        updateStmt.setString(1, status);
                        updateStmt.setString(2, userStudentNo);
                        updateStmt.setString(3, tutorName);
                        int rowsAffected = updateStmt.executeUpdate();
                        if (rowsAffected > 0) {
                            // Send email to the requester
                            String emailQuery = "SELECT EMAIL FROM PROFILE WHERE STUDENT_NO = ?";
                            try (PreparedStatement emailStmt = con.prepareStatement(emailQuery)) {
                                emailStmt.setString(1, userStudentNo);
                                try (ResultSet rs = emailStmt.executeQuery()) {
                                    if (rs.next()) {
                                        String toEmail = rs.getString("EMAIL");

                                        // Construct email body
                                        String subject = "ITBS: Tutorial Request Status";
                                        String body = "We regret to inform you that your tutorial request has been " + status.toLowerCase() + " by the tutor. \n Reason: "+ reason + "\n";
                                        body += "Thank you for using our service.";

                                        // Send email
                                        OTPGenerator email = new OTPGenerator(); // Assuming OTPGenerator is your email sending utility
                                        email.sendEmail(toEmail, subject , body);

                                        JOptionPane.showMessageDialog(null, "Response sent successfully to " + toEmail);
                                    }
                                }
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "Failed to update status.");
                        }
                    }
                } catch (SQLException err) {
                    JOptionPane.showMessageDialog(null, "Error: " + err.getMessage());
                }
            } else {
                JOptionPane.showMessageDialog(null, "Please select a row to approve or reject.");
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        String status = "Approved"; // or "Rejected" as per your requirement

// Assuming your JTable instance is named "TDisplayStudents"
        int selectedRow = TDisplayStudents.getSelectedRow();
        if (selectedRow != -1) {
            try {
                DefaultTableModel model = (DefaultTableModel) TDisplayStudents.getModel();
                String userStudentNo = (String) model.getValueAt(selectedRow, 1);
                String tutorResponse = status; // Assuming the status is set to "Approved" or "Rejected" as per your requirement

                String host = "jdbc:derby://localhost:1527/Tutorilas";
                String uName = "user1";
                String uPass = "user1";
                con = DriverManager.getConnection(host, uName, uPass);

                // Update the status in the database
                String updateQuery = "UPDATE TUTORIAL_REQUESTS SET STATUS = ? WHERE STUDENT_NO = ?";
                try (PreparedStatement updateStmt = con.prepareStatement(updateQuery)) {
                    updateStmt.setString(1, status);
                    updateStmt.setString(2, userStudentNo);
                    int rowsAffected = updateStmt.executeUpdate();
                    if (rowsAffected > 0) {
                        // Send email to the requester
                        String emailQuery = "SELECT EMAIL FROM PROFILE WHERE STUDENT_NO = ?";
                        try (PreparedStatement emailStmt = con.prepareStatement(emailQuery)) {
                            emailStmt.setString(1, userStudentNo);
                            try (ResultSet rs = emailStmt.executeQuery()) {
                                if (rs.next()) {
                                    String toEmail = rs.getString("EMAIL");

                                    // Construct email body
                                    String subject = "ITBS: Tutorial Request Status";
                                    String body = "Congratulations, we would like to inform you that your tutorial request has been " + status.toLowerCase() + " by the tutor. Log into your portal to view more information\n";
                                    body += "Thank you for using our service.";

                                    // Send email
                                    OTPGenerator email = new OTPGenerator(); // Assuming OTPGenerator is your email sending utility
                                    email.sendEmail(toEmail, subject, body);

                                    JOptionPane.showMessageDialog(null, "Response sent successfully to " + toEmail);
                                }
                            }
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Failed to update status.");
                    }
                }
            } catch (SQLException err) {
                JOptionPane.showMessageDialog(null, "Error: " + err.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row to approve or reject.");
        }

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jLabel13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_jLabel13MouseEntered

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        studentDashboard dash = new studentDashboard();
        dash.setTitle("Student Dashboard");
        dash.setVisible(true);
    }//GEN-LAST:event_jLabel13MouseClicked

    private void JProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JProfileActionPerformed
        // TODO add your handling code here:
        JTabbedPane.setSelectedIndex(0);

    }//GEN-LAST:event_JProfileActionPerformed

    private void JRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRequestsActionPerformed
        // TODO add your handling code here:
        JTabbedPane.setSelectedIndex(1);
        try {
            String host = "jdbc:derby://localhost:1527/Tutorilas";
            String uName = "user1";
            String uPass = "user1";
            con = DriverManager.getConnection(host, uName, uPass);

            ProfileClass prof = new ProfileClass();
            String StudentNo = prof.getStudentNo();

            String query = "SELECT STUDENT_YEAR, MODULE, TUTOR_NAME, PREFERED_MODE, TIME, DATE, STUDENT_NO, STATUS FROM TUTORIAL_REQUESTS WHERE TUTOR_NAME = ?";

            try (PreparedStatement pstmt = con.prepareStatement(query)) {
                pstmt.setString(1, StudentNo);

                try (ResultSet rs = pstmt.executeQuery()) {
                    DefaultTableModel table = (DefaultTableModel) TDisplayStudents.getModel();
                    table.setRowCount(0);

                    while (rs.next()) {

                        String name = rs.getString("TUTOR_NAME");
                        String studentNo = rs.getString("STUDENT_NO");
                        String module = rs.getString("MODULE");
                        String mode = rs.getString("PREFERED_MODE");
                        String time = rs.getString("TIME");
                        String date = rs.getString("DATE");
                        String status = rs.getString("STATUS");

                        String[] rowData = {name, studentNo, module, mode, time, date, status};
                        table.addRow(rowData);

                    }
                }
            } catch (SQLException err) {
                JOptionPane.showMessageDialog(null, err.getMessage());
            }
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, err.getMessage());
        }
    }//GEN-LAST:event_JRequestsActionPerformed

    private void JAppointmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JAppointmentsActionPerformed
        // TODO add your handling code here:
        JTabbedPane.setSelectedIndex(2);
        try {
            String host = "jdbc:derby://localhost:1527/Tutorilas";
            String uName = "user1";
            String uPass = "user1";
            con = DriverManager.getConnection(host, uName, uPass);

            String status = "Approved";
            ProfileClass prof = new ProfileClass();
            String tutorName = prof.getStudentNo();

            String query = "SELECT STUDENT_YEAR, MODULE, TUTOR_NAME, PREFERED_MODE, TIME, DATE, STUDENT_NO, STATUS FROM TUTORIAL_REQUESTS WHERE STATUS = ? AND TUTOR_NAME = ?";

            try (PreparedStatement pstmt = con.prepareStatement(query)) {
                pstmt.setString(1, status);
                pstmt.setString(2, tutorName);

                try (ResultSet rs = pstmt.executeQuery()) {
                    DefaultTableModel table = (DefaultTableModel) TApprovedStudents.getModel();
                    table.setRowCount(0);

                    while (rs.next()) {
                        String name = rs.getString("STUDENT_YEAR");
                        String studentNo = rs.getString("STUDENT_NO");
                        String module = rs.getString("MODULE");
                        String mode = rs.getString("PREFERED_MODE");
                        String time = rs.getString("TIME");
                        String date = rs.getString("DATE");
                        String dbDtatus = rs.getString("STATUS");

                        String[] rowData = {name, studentNo, module, mode, time, date, dbDtatus};
                        table.addRow(rowData);

                    }
                }
            } catch (SQLException err) {
                JOptionPane.showMessageDialog(null, err.getMessage());
            }
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, err.getMessage());
        }
    }//GEN-LAST:event_JAppointmentsActionPerformed

    private void JClaimsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JClaimsActionPerformed
        // TODO add your handling code here:
        JTabbedPane.setSelectedIndex(3);

    }//GEN-LAST:event_JClaimsActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        String tutorName = tfTutorName.getText();
        String studentName = tfStudentName.getText();
        String tutorialHours = tfDuration.getText();
        int hours = Integer.parseInt(tutorialHours);
        String module = tfModule.getText();
        double rate = 50.0;

        double totalAmount = hours * rate;

        try {
            String host = "jdbc:derby://localhost:1527/Tutorilas";
            String uName = "user1";
            String uPass = "user1";
            con = DriverManager.getConnection(host, uName, uPass);

            String query = "INSERT INTO PAYMENTS (TUTOR_NAME, STUDENT_NAME, TUTORIAL_HOURS, MODULE, TOTAL_PRICE) VALUES(?,?,?,?,?)";
            PreparedStatement ps = con.prepareStatement(query);

            ps.setString(1, tutorName);
            ps.setString(2, studentName);
            ps.setInt(3, hours);
            ps.setString(4, module);
            ps.setDouble(5, totalAmount);

            int rowsAffected = ps.executeUpdate();

            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(this, "The session costed " + totalAmount + ".");
            } else {
                JOptionPane.showMessageDialog(this, "Submission Failed failed!");
            }

            // Close resources
            ps.close();
            con.close();

        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, err.getMessage());
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void JAcademicLevelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JAcademicLevelMouseClicked
        // TODO add your handling code here:
        try {
            String host = "jdbc:derby://localhost:1527/Tutorilas";
            String uName = "user1";
            String uPass = "user1";
            con = DriverManager.getConnection(host, uName, uPass);

            ProfileClass prof = new ProfileClass();
            String stud = prof.getStudentNo();

            String query = "SELECT COURSE, ACADEMIC_LEVEL FROM PROFILE Where STUDENT_NO = ?";
            try (PreparedStatement pstmt = con.prepareStatement(query)) {
                pstmt.setString(1, stud);
                try (ResultSet rs = pstmt.executeQuery()) {
                    if (rs.next()) {
                        String course = rs.getString("COURSE");
                        String level = rs.getString("ACADEMIC_LEVEL");

                        JAcademicLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{level}));

                        if (course.equals("Dip In ICT") && level.equals("1st Year")) {
                            tfModules.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Applications Development", "Web Development", "ICT Fundamentals", "Programming I", "Information Systems I", "Neworking", "Core Curriculum I", "Core Curriculum II", "Business Practice"}));
                        } else if (course.equals("Dip In ICT") && level.equals("2nd Year")) {
                            tfModules.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Programming II", "Software Engineering", "Informaltion Systems II", "Android Development", "TechnoPreneurShips", "Big Data", "Web Developmeng II", "Professional Communication", "Project Management"}));
                        } else if (course.equals("Dip In ICT") && level.equals("3rd Year")) {
                            tfModules.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Programming III", "Software Engineering II", "Informaltion Systems III", "Data Analysis And Visualization", "Human Computer Interaction", "Project"}));
                        } else if (course.equals("Dip In ICT") && level.equals("4th Year")) {
                            tfModules.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Advanced Data Analysis And Visualization", "Database System", "Development Software", "Project", "Advanced development software", "Software Engineering", "Information Security"}));
                        } else if (course.equals("Data Science") && level.equals("1st Year")) {
                            tfModules.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Introduction To Statistics", "Calculus", "Basic Computer Organization And Architecture", "Probability Theory", "Introduction Programming In C++", "Algebra", "Core Curriculum", "Core Curriculum II", "Data Science I"}));
                        } else if (course.equals("Data Science") && level.equals("2nd Year")) {
                            tfModules.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Advance Calculus", "Distribution Theory", "Algorith Analysis And Program", "Database Systems", "Linear Algebra", "Discrete Mathematics", "Statistical Inference", "Operating Systems and Computer Networks", " "}));
                        }
                        if (course.equals("Data Science") && level.equals("3rd Year")) {
                            tfModules.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Advance Algorithm Analysis", "Data Security", "Algorith Analysis And Programming", "Database Systems", "Linea r Algebra", "Mathematics Analysis", "Statistical Inference"}));
                        }
                        if (course.equals("Computer Science") && level.equals("1st Year")) {
                            tfModules.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Calculus", "Mechanics", "Basic Computer Organization", "Core Corriculum I", "Algebra", "Numerical Methods and Mathematical Modeling", "Probability Theory", "Core Corriculum II"}));
                        }
                        if (course.equals("Computer Science") && level.equals("2nd Year")) {
                            tfModules.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Advance Calculus", "Distribution Theory", "Algorith Analysis And Program", "Database Systems", "Linear Algebra", "Discrete Mathematics", "Statistical Inference", "Operating Systems and Computer Networks"}));
                        }
                        if (course.equals("Computer Science") && level.equals("3rd Year")) {
                            tfModules.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Advance Algorithm Analysis", "Data Security", "Algorith Analysis And Programming", "Database Systems", "Linea r Algebra", "Mathematics Analysis", "Statistical Inference"}));
                        }
                    }
                }
            }
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, err.getMessage());
        }
    }//GEN-LAST:event_JAcademicLevelMouseClicked

    private void JProfileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JProfileMouseEntered
        // TODO add your handling code here:
        JProfile.setBackground(new Color(204,153,0));
    }//GEN-LAST:event_JProfileMouseEntered

    private void JProfileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JProfileMouseExited
        // TODO add your handling code here:
        JProfile.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_JProfileMouseExited

    private void JRequestsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JRequestsMouseEntered
        // TODO add your handling code here:
        JRequests.setBackground(new Color(204,153,0));
    }//GEN-LAST:event_JRequestsMouseEntered

    private void JRequestsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JRequestsMouseExited
        // TODO add your handling code here:
        JRequests.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_JRequestsMouseExited

    private void JAppointmentsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JAppointmentsMouseEntered
        // TODO add your handling code here:
        JAppointments.setBackground(new Color(204,153,0));
    }//GEN-LAST:event_JAppointmentsMouseEntered

    private void JAppointmentsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JAppointmentsMouseExited
        // TODO add your handling code here:
        JAppointments.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_JAppointmentsMouseExited

    private void JClaimsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JClaimsMouseEntered
        // TODO add your handling code here:
        JClaims.setBackground(new Color(204,153,0));
    }//GEN-LAST:event_JClaimsMouseEntered

    private void JClaimsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JClaimsMouseExited
        // TODO add your handling code here:
        JClaims.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_JClaimsMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tutorDash.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tutorDash.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tutorDash.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tutorDash.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tutorDash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JAcademicLevel;
    private javax.swing.JButton JAppointments;
    private javax.swing.JComboBox<String> JAvailableSlot;
    private javax.swing.JButton JClaims;
    private javax.swing.JComboBox<String> JCourse;
    private javax.swing.JComboBox<String> JPreferredMode;
    private javax.swing.JButton JProfile;
    private javax.swing.JTextField JReason;
    private javax.swing.JButton JRequests;
    private javax.swing.JTabbedPane JTabbedPane;
    private javax.swing.JPanel JTabbedRequests;
    private javax.swing.JTable TApprovedStudents;
    private javax.swing.JTable TDisplayStudents;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField tfDuration;
    private javax.swing.JTextField tfModule;
    private javax.swing.JComboBox<String> tfModules;
    private javax.swing.JTextField tfStudentName;
    private javax.swing.JTextField tfTutorName;
    // End of variables declaration//GEN-END:variables
}
